import { V3UnitOfWork } from '../../storage/unit-of-work.mjs';
import { requireEventScope } from '../events/event-validator.mjs';
import { canonicalJson, requestDigest } from '../events/idempotency.mjs';
import { prepareDisclosureBundle } from '../knowledge/knowledge-service.mjs';
import { AUDIENCE_KIND } from '../knowledge/audience-policy.mjs';
import { EVIDENCE_BASIS } from '../knowledge/disclosure-observation.mjs';
import { EVIDENCE_FRAGMENT_KIND } from '../knowledge/evidence-fragment.mjs';
import { emptyStoryClock, storyClockHeadId } from '../time/clock-projector.mjs';
import { normalizeSocialPersona } from './social-persona.mjs';
import { normalizeSocialGraphEdge, SOCIAL_RELATION } from './social-graph.mjs';
import { normalizeSocialAudience, SOCIAL_AUDIENCE, socialAudiencePermits } from './audience.mjs';
import { normalizeSocialPost, socialPostHeadId } from './post.mjs';
import { normalizeSocialComment, socialCommentHeadId } from './comment.mjs';
import { ENGAGEMENT_KIND, normalizeSocialEngagement } from './engagement.mjs';
import { socialDecision } from './social-decision.mjs';
import { SOCIAL_EVENT_TYPES } from './social-event-types.mjs';

const MAX_SEQUENCE = Number.MAX_SAFE_INTEGER;
const stableId = async (kind, scope, value) => `${kind}:${(await requestDigest({ kind, scope, value })).slice(0, 40)}`;
const uniqueReferences = references => Object.freeze([...new Map(references.filter(Boolean).map(row => [`${row.entityType}:${row.id}:${row.role}`, row])).values()]);

export class SocialService {
  #unit; #events; #metrics = Object.freeze({ operation: 'none' });
  constructor({ database, eventEngine }) { if (!database || !eventEngine) throw new TypeError('SocialService requires isolated storage and canonical Events'); this.#unit = new V3UnitOfWork(database); this.#events = eventEngine; }
  get lastMetrics() { return structuredClone(this.#metrics); }

  async #accountBinding(scope, accountId) { return this.#unit.readonly({ stores: ['accounts', 'instances', 'actors'], scope }, async repositories => { const account = await repositories.accounts.get(accountId); const instance = account ? await repositories.instances.get(account.ownerInstanceId) : null; const actor = instance ? await repositories.actors.get(instance.actorId) : null; if (!account || !instance || !actor) throw new Error('Social Account identity is unknown or cross-scope'); return Object.freeze({ accountId: account.id, instanceId: instance.id, actorId: actor.id }); }); }
  async #storyTime(scope) { return this.#unit.readonly({ stores: ['clockCheckpoints'], scope }, async repositories => (await repositories.clockCheckpoints.get(storyClockHeadId(scope)))?.state?.storyTimeRef || emptyStoryClock(scope).storyTimeRef); }
  async #isBlocked(scope, left, right) { if (left === right) return false; return this.#unit.readonly({ stores: ['socialGraphEdges'], scope }, async repositories => { for (const [owner, target] of [[left, right], [right, left]]) for (const relation of [SOCIAL_RELATION.BLOCK, SOCIAL_RELATION.RESTRICT]) { const row = await repositories.socialGraphEdges.getByIndex('by_scope_owner_target_relation', [scope.storyId, scope.branchId, owner, target, relation]); if (row?.active) return true; } return false; }); }
  async #audienceSnapshot(scope, authorAccountId, input) { const kind = String(input?.kind || '').trim(); let candidates = [...(input?.recipientAccountIds || [])]; if (kind === SOCIAL_AUDIENCE.FOLLOWERS) candidates = (await this.#unit.readonly({ stores: ['socialGraphEdges'], scope }, repositories => repositories.socialGraphEdges.listByIndex('by_scope_target_relation', [scope.storyId, scope.branchId, authorAccountId, SOCIAL_RELATION.FOLLOW, 'active']))).map(row => row.ownerAccountId); if (kind === SOCIAL_AUDIENCE.CLOSE_FRIENDS) candidates = (await this.#unit.readonly({ stores: ['socialGraphEdges'], scope }, repositories => repositories.socialGraphEdges.listByIndex('by_scope_owner_relation', [scope.storyId, scope.branchId, authorAccountId, SOCIAL_RELATION.CLOSE_FRIEND, 'active']))).map(row => row.targetAccountId); const safe = []; for (const accountId of [...new Set(candidates)]) if (!(await this.#isBlocked(scope, authorAccountId, accountId))) safe.push(accountId); return normalizeSocialAudience({ ...input, kind, recipientAccountIds: safe }); }
  async resolveAudience({ scope: inputScope, authorAccountId, audience }) { const scope = requireEventScope(inputScope); await this.#accountBinding(scope, authorAccountId); return this.#audienceSnapshot(scope, authorAccountId, audience); }
  async #disclosure(scope, subjectId, text, author, audience, source, recipientBindings) { const people = audience.kind === SOCIAL_AUDIENCE.PUBLIC ? [author] : [...new Map([author, ...recipientBindings].map(row => [row.accountId, row])).values()]; return prepareDisclosureBundle({ scope, stableKey: `social:${subjectId}`, bundle: { claim: { claimType: 'social.visible-content.v1', subject: { kind: 'event', id: subjectId }, safeSummary: text || '[Social post]', certainty: 'confirmed', currentness: 'current' }, audience: { kind: audience.kind === SOCIAL_AUDIENCE.PUBLIC ? AUDIENCE_KIND.PUBLIC_STORY : AUDIENCE_KIND.PRIVATE_EXPLICIT, actorIds: people.map(row => row.actorId), instanceIds: people.map(row => row.instanceId) }, fragments: [{ key: 'content', kind: EVIDENCE_FRAGMENT_KIND.EVENT_FIELD, safeText: text || '[Social post]', sourceField: 'text' }], observations: people.map(person => ({ fragmentKeys: ['content'], targetActorId: person.actorId, targetInstanceId: person.instanceId, confidence: 'confirmed', evidence: { basis: person.accountId === author.accountId ? EVIDENCE_BASIS.DIRECT_PARTICIPANT : EVIDENCE_BASIS.PUBLIC_EXPOSURE, sourceEventId: null, sourceActorId: author.actorId, sourceDeviceId: null, sourceAccountId: author.accountId, provenanceAuthority: source.authority, provenanceRecordId: `${source.recordId}:knowledge:${person.accountId}` } })) } }); }

  async setPersona({ scope: inputScope, actorId, instanceId, accountId, persona, source, producer = 'social-service', idempotencyKey }) { const scope = requireEventScope(inputScope); const binding = await this.#accountBinding(scope, accountId); if (binding.actorId !== actorId || binding.instanceId !== instanceId) throw new Error('Social Persona Actor/Instance/Account mismatch'); const personaId = await stableId('social-persona', scope, { actorId, instanceId, accountId }); const normalized = normalizeSocialPersona({ personaId, actorId, instanceId, accountId, ...persona }); const existing = await this.getPersona({ scope, accountId }); const payload = { persona: normalized }; let result; if (existing) { const event = await this.#events.getEvent(scope, existing.sourceEventId); result = canonicalJson(event.payload) === canonicalJson(payload) ? { event, replayed: true } : await this.#events.revise({ scope, eventId: event.id, expectedRevision: event.revision, payload, producer, idempotencyKey, reason: 'Social Persona update' }); } else result = await this.#events.append({ scope, eventType: SOCIAL_EVENT_TYPES.PERSONA_STATE, payload, references: [{ entityType: 'actor', id: actorId, role: 'social-persona-actor' }, { entityType: 'character-instance', id: instanceId, role: 'social-persona-instance' }, { entityType: 'account', id: accountId, role: 'social-persona-account' }], source, producer, idempotencyKey }); return Object.freeze({ persona: await this.getPersona({ scope, accountId }), event: result.event, replayed: result.replayed }); }
  async setActorPersona({ scope: inputScope, actorId, persona, source, producer = 'social-service', idempotencyKey }) { const scope = requireEventScope(inputScope); const actor = await this.#unit.readonly({ stores: ['actors'], scope }, repositories => repositories.actors.get(actorId)); if (!actor) throw new Error('Social Persona Actor is unknown'); const personaId = await stableId('social-persona-base', scope, { actorId }); const normalized = normalizeSocialPersona({ personaId, actorId, sourceLevel: 'actor-base', ...persona }); const existing = (await this.#unit.readonly({ stores: ['socialPersonas'], scope }, repositories => repositories.socialPersonas.listByIndex('by_scope_actor', [scope.storyId, scope.branchId, actorId]))).find(row => row.sourceLevel === 'actor-base'); const payload = { persona: normalized }; let result; if (existing) { const event = await this.#events.getEvent(scope, existing.sourceEventId); result = canonicalJson(event.payload) === canonicalJson(payload) ? { event, replayed: true } : await this.#events.revise({ scope, eventId: event.id, expectedRevision: event.revision, payload, producer, idempotencyKey, reason: 'Actor Social Persona update' }); } else result = await this.#events.append({ scope, eventType: SOCIAL_EVENT_TYPES.PERSONA_STATE, payload, references: [{ entityType: 'actor', id: actorId, role: 'social-persona-actor-base' }], source, producer, idempotencyKey }); return Object.freeze({ persona: normalized, event: result.event, replayed: result.replayed }); }
  async getPersona({ scope: inputScope, accountId }) { const scope = requireEventScope(inputScope); return (await this.#unit.readonly({ stores: ['socialPersonas'], scope }, repositories => repositories.socialPersonas.getByIndex('by_scope_account', [scope.storyId, scope.branchId, accountId]))) || null; }
  async getEffectivePersona({ scope: inputScope, actorId, accountId }) { const scope = requireEventScope(inputScope); const rows = await this.#unit.readonly({ stores: ['socialPersonas'], scope }, repositories => repositories.socialPersonas.listByIndex('by_scope_actor', [scope.storyId, scope.branchId, actorId])); const base = rows.find(row => row.sourceLevel === 'actor-base') || {}; const instance = rows.find(row => row.accountId === accountId && row.sourceLevel === 'story-instance') || {}; if (!base.personaId && !instance.personaId) return null; return Object.freeze({ ...base, ...instance, personaId: instance.personaId || base.personaId, actorId, accountId, inheritance: Object.freeze({ actorBaseEventId: base.sourceEventId || null, instanceOverrideEventId: instance.sourceEventId || null }) }); }

  async setGraphEdge({ scope: inputScope, ownerAccountId, targetAccountId, relation, active = true, source, producer = 'social-service', idempotencyKey }) { const scope = requireEventScope(inputScope); await Promise.all([this.#accountBinding(scope, ownerAccountId), this.#accountBinding(scope, targetAccountId)]); const edgeId = await stableId('social-edge', scope, { ownerAccountId, targetAccountId, relation }); const edge = normalizeSocialGraphEdge({ edgeId, ownerAccountId, targetAccountId, relation, active }); const existing = await this.#unit.readonly({ stores: ['socialGraphEdges'], scope }, repositories => repositories.socialGraphEdges.getByIndex('by_scope_owner_target_relation', [scope.storyId, scope.branchId, ownerAccountId, targetAccountId, relation])); const payload = { edge }; let result; if (existing) { const event = await this.#events.getEvent(scope, existing.sourceEventId); result = canonicalJson(event.payload) === canonicalJson(payload) ? { event, replayed: true } : await this.#events.revise({ scope, eventId: event.id, expectedRevision: event.revision, payload, producer, idempotencyKey, reason: 'Social graph state change' }); } else result = await this.#events.append({ scope, eventType: SOCIAL_EVENT_TYPES.GRAPH_STATE, payload, references: [{ entityType: 'account', id: ownerAccountId, role: 'social-edge-owner' }, { entityType: 'account', id: targetAccountId, role: 'social-edge-target' }], source, producer, idempotencyKey }); return Object.freeze({ edge: await this.#unit.readonly({ stores: ['socialGraphEdges'], scope }, repositories => repositories.socialGraphEdges.get(edgeId)), event: result.event, replayed: result.replayed }); }

  async createPost({ scope: inputScope, authorAccountId, actualAuthorActorId, actualAuthorInstanceId, deviceId, text = '', assetRefs = [], audience: audienceInput = { kind: SOCIAL_AUDIENCE.PUBLIC }, audienceSnapshot = null, source, producer = 'social-service', idempotencyKey, causeEventIds = [], aiJobCommit = null }) { const scope = requireEventScope(inputScope); const author = await this.#accountBinding(scope, authorAccountId); if (author.actorId !== actualAuthorActorId || author.instanceId !== actualAuthorInstanceId) throw new Error('Post actual Author identity mismatch'); const device = await this.#unit.readonly({ stores: ['devices'], scope }, repositories => repositories.devices.get(deviceId)); if (!device) throw new Error('Post Device is unknown or cross-scope'); const audience = audienceSnapshot ? normalizeSocialAudience(audienceSnapshot) : await this.#audienceSnapshot(scope, authorAccountId, audienceInput); const recipients = await Promise.all(audience.recipientAccountIds.map(accountId => this.#accountBinding(scope, accountId))); const postId = await stableId('social-post', scope, { authority: source.authority, recordId: source.recordId, authorAccountId }); const post = normalizeSocialPost({ postId, authorAccountId, actualAuthorActorId, actualAuthorInstanceId, deviceId, text, assetRefs, audience, storyTimeRef: await this.#storyTime(scope), aiJobId: aiJobCommit?.jobId || null }); const bundle = await this.#disclosure(scope, postId, post.text, author, audience, source, recipients); const result = await this.#events.append({ scope, eventType: SOCIAL_EVENT_TYPES.POST_CREATED, payload: { post, knowledgeDisclosures: [bundle], ...(aiJobCommit ? { aiJobCommit } : {}) }, references: uniqueReferences([{ entityType: 'account', id: authorAccountId, role: 'post-author-account' }, { entityType: 'actor', id: actualAuthorActorId, role: 'post-actual-author' }, { entityType: 'character-instance', id: actualAuthorInstanceId, role: 'post-actual-author-instance' }, { entityType: 'device', id: deviceId, role: 'post-device' }, ...recipients.map(row => ({ entityType: 'account', id: row.accountId, role: 'post-audience-account' }))]), causes: [...new Set([...(causeEventIds || []), aiJobCommit?.sourceEventId].filter(Boolean))], source, producer, idempotencyKey: idempotencyKey || `post:${postId}` }); return Object.freeze({ post: await this.getPost({ scope, postId }), event: result.event, replayed: result.replayed }); }
  async editPost({ scope: inputScope, postId, text, audience: audienceInput = null, producer = 'social-service', idempotencyKey, reason = 'Post edit' }) { const scope = requireEventScope(inputScope); const head = await this.getPost({ scope, postId }); if (!head) throw new Error('Unknown scoped post'); const event = await this.#events.getEvent(scope, head.sourceEventId); const author = await this.#accountBinding(scope, head.authorAccountId); const audience = audienceInput ? await this.#audienceSnapshot(scope, head.authorAccountId, audienceInput) : head.audience; const recipients = await Promise.all(audience.recipientAccountIds.map(accountId => this.#accountBinding(scope, accountId))); const post = normalizeSocialPost({ ...head, text, audience }); const bundle = await this.#disclosure(scope, postId, post.text, author, audience, { authority: event.provenance.authority, recordId: event.provenance.recordId }, recipients); const result = await this.#events.revise({ scope, eventId: event.id, expectedRevision: event.revision, payload: { ...event.payload, post, knowledgeDisclosures: [bundle] }, producer, idempotencyKey, reason }); return Object.freeze({ post: await this.getPost({ scope, postId }), event: result.event, replayed: result.replayed }); }
  async getPost({ scope: inputScope, postId }) { const scope = requireEventScope(inputScope); return (await this.#unit.readonly({ stores: ['socialPosts'], scope }, repositories => repositories.socialPosts.get(socialPostHeadId(scope, postId)))) || null; }

  async createComment({ scope: inputScope, postId, parentCommentId = null, authorAccountId, actualAuthorActorId, actualAuthorInstanceId, deviceId, text, source, producer = 'social-service', idempotencyKey, aiJobCommit = null }) { const scope = requireEventScope(inputScope); const post = await this.getPost({ scope, postId }); if (!post) throw new Error('Unknown or non-current scoped post'); const author = await this.#accountBinding(scope, authorAccountId); if (author.actorId !== actualAuthorActorId || author.instanceId !== actualAuthorInstanceId || !socialAudiencePermits(post.audience, authorAccountId)) throw new Error('Comment Author is outside the post Audience'); let parent = null; if (parentCommentId) { parent = await this.getComment({ scope, commentId: parentCommentId }); if (!parent || parent.postId !== postId) throw new Error('Reply parent must be a current comment on this post'); } const commentId = await stableId('social-comment', scope, { authority: source.authority, recordId: source.recordId, authorAccountId }); const comment = normalizeSocialComment({ commentId, postId, parentCommentId, authorAccountId, actualAuthorActorId, actualAuthorInstanceId, deviceId, text, storyTimeRef: await this.#storyTime(scope), aiJobId: aiJobCommit?.jobId || null }); const recipients = await Promise.all(post.audience.recipientAccountIds.map(accountId => this.#accountBinding(scope, accountId))); const bundle = await this.#disclosure(scope, commentId, text, author, post.audience, source, recipients); const result = await this.#events.append({ scope, eventType: SOCIAL_EVENT_TYPES.COMMENT_CREATED, payload: { comment, recipientAccountIds: post.audience.recipientAccountIds, knowledgeDisclosures: [bundle], ...(aiJobCommit ? { aiJobCommit } : {}) }, references: uniqueReferences([{ entityType: 'account', id: authorAccountId, role: 'comment-author-account' }, { entityType: 'actor', id: actualAuthorActorId, role: 'comment-actual-author' }, { entityType: 'character-instance', id: actualAuthorInstanceId, role: 'comment-author-instance' }, { entityType: 'device', id: deviceId, role: 'comment-device' }]), causes: [...new Set([post.sourceEventId, parent?.sourceEventId, aiJobCommit?.sourceEventId].filter(Boolean))], source, producer, idempotencyKey: idempotencyKey || `comment:${commentId}` }); return Object.freeze({ comment: await this.getComment({ scope, commentId }), event: result.event, replayed: result.replayed }); }
  async editComment({ scope: inputScope, commentId, text, producer = 'social-service', idempotencyKey, reason = 'Comment edit' }) { const scope = requireEventScope(inputScope); const head = await this.getComment({ scope, commentId }); if (!head) throw new Error('Unknown scoped comment'); const event = await this.#events.getEvent(scope, head.sourceEventId); const post = await this.getPost({ scope, postId: head.postId }); const author = await this.#accountBinding(scope, head.authorAccountId); const recipients = await Promise.all(post.audience.recipientAccountIds.map(accountId => this.#accountBinding(scope, accountId))); const comment = normalizeSocialComment({ ...head, text }); const bundle = await this.#disclosure(scope, commentId, text, author, post.audience, { authority: event.provenance.authority, recordId: event.provenance.recordId }, recipients); const result = await this.#events.revise({ scope, eventId: event.id, expectedRevision: event.revision, payload: { ...event.payload, comment, knowledgeDisclosures: [bundle] }, producer, idempotencyKey, reason }); return Object.freeze({ comment: await this.getComment({ scope, commentId }), event: result.event, replayed: result.replayed }); }
  async getComment({ scope: inputScope, commentId }) { const scope = requireEventScope(inputScope); return (await this.#unit.readonly({ stores: ['socialComments'], scope }, repositories => repositories.socialComments.get(socialCommentHeadId(scope, commentId)))) || null; }

  async setEngagement({ scope: inputScope, targetId, targetKind = 'post', kind = ENGAGEMENT_KIND.LIKE, actorAccountId, actualActorId, actualInstanceId, active = true, quoteText = null, source, producer = 'social-service', idempotencyKey, aiJobCommit = null, causeEventIds = [] }) { const scope = requireEventScope(inputScope); const post = targetKind === 'post' ? await this.getPost({ scope, postId: targetId }) : await this.getComment({ scope, commentId: targetId }).then(comment => comment && this.getPost({ scope, postId: comment.postId })); if (!post || !socialAudiencePermits(post.audience, actorAccountId) || await this.#isBlocked(scope, post.authorAccountId, actorAccountId)) throw new Error('Engagement Actor cannot access this target'); const binding = await this.#accountBinding(scope, actorAccountId); if (binding.actorId !== actualActorId || binding.instanceId !== actualInstanceId) throw new Error('Engagement actual Actor mismatch'); const engagementId = await stableId('social-engagement', scope, { targetId, actorAccountId, kind }); const engagement = normalizeSocialEngagement({ engagementId, targetId, targetKind, kind, actorAccountId, actualActorId, actualInstanceId, active, quoteText }); const existing = await this.#unit.readonly({ stores: ['socialEngagements'], scope }, repositories => repositories.socialEngagements.getByIndex('by_scope_target_account_kind', [scope.storyId, scope.branchId, targetId, actorAccountId, kind])); const payload = { engagement, ...(aiJobCommit ? { aiJobCommit } : {}) }; let result; if (existing) { const event = await this.#events.getEvent(scope, existing.sourceEventId); result = canonicalJson(event.payload) === canonicalJson(payload) ? { event, replayed: true } : await this.#events.revise({ scope, eventId: event.id, expectedRevision: event.revision, payload, producer, idempotencyKey, reason: 'Social engagement state change' }); } else result = await this.#events.append({ scope, eventType: SOCIAL_EVENT_TYPES.ENGAGEMENT_STATE, payload, references: [{ entityType: 'account', id: actorAccountId, role: 'engagement-account' }, { entityType: 'actor', id: actualActorId, role: 'engagement-actual-actor' }, { entityType: 'character-instance', id: actualInstanceId, role: 'engagement-instance' }], causes: [...new Set([post.sourceEventId, ...(causeEventIds || []), aiJobCommit?.sourceEventId].filter(Boolean))], source, producer, idempotencyKey }); return Object.freeze({ engagement: await this.#unit.readonly({ stores: ['socialEngagements'], scope }, repositories => repositories.socialEngagements.get(engagementId)), event: result.event, replayed: result.replayed }); }

  async recordDecision({ scope: inputScope, triggerEventId, actorInstanceId, persona, publicSafe = false, reason, source, producer = 'social-service', idempotencyKey }) { const scope = requireEventScope(inputScope); const decision = socialDecision({ triggerEventId, actorInstanceId, persona, publicSafe, reason }); const result = await this.#events.append({ scope, eventType: SOCIAL_EVENT_TYPES.DECISION_RECORDED, payload: { decision }, references: [{ entityType: 'character-instance', id: actorInstanceId, role: 'social-decision-instance' }], causes: [triggerEventId], source, producer, idempotencyKey }); return Object.freeze({ decision, event: result.event, replayed: result.replayed }); }

  async listFeed({ scope: inputScope, viewerAccountId, limit = 20, cursor = 0 }) { const scope = requireEventScope(inputScope); if (!Number.isInteger(limit) || limit < 1 || limit > 50) throw new TypeError('Feed limit must be 1–50'); const lowerCursor = Number(cursor || 0); const result = await this.#unit.readonly({ stores: ['socialPosts', 'socialPostRecipients', 'socialGraphEdges'], scope }, async repositories => { const publicRows = await repositories.socialPosts.listByIndexRange('by_scope_audience_reverse_sequence', { lower: [scope.storyId, scope.branchId, SOCIAL_AUDIENCE.PUBLIC, 'current', lowerCursor], upper: [scope.storyId, scope.branchId, SOCIAL_AUDIENCE.PUBLIC, 'current', MAX_SEQUENCE] }, { limit: limit * 2 }); const recipientRows = await repositories.socialPostRecipients.listByIndexRange('by_scope_account_reverse_sequence', { lower: [scope.storyId, scope.branchId, viewerAccountId, lowerCursor], upper: [scope.storyId, scope.branchId, viewerAccountId, MAX_SEQUENCE] }, { limit }); const restricted = await Promise.all(recipientRows.map(row => repositories.socialPosts.get(socialPostHeadId(scope, row.postId)))); const merged = [...new Map([...publicRows, ...restricted.filter(Boolean)].map(row => [row.postId, row])).values()].sort((a, b) => a.reverseSequence - b.reverseSequence || a.postId.localeCompare(b.postId)); const visible = []; let relationshipIndexReads = 0; for (const post of merged) { const blocked = await Promise.all([[post.authorAccountId, viewerAccountId], [viewerAccountId, post.authorAccountId]].flatMap(([owner, target]) => [SOCIAL_RELATION.BLOCK, SOCIAL_RELATION.RESTRICT].map(relation => repositories.socialGraphEdges.getByIndex('by_scope_owner_target_relation', [scope.storyId, scope.branchId, owner, target, relation])))); relationshipIndexReads += 4; if (!blocked.some(row => row?.active)) visible.push(post); if (visible.length === limit) break; } return { visible, publicRowsRead: publicRows.length, recipientRowsRead: recipientRows.length, relationshipIndexReads }; }); this.#metrics = Object.freeze({ operation: 'list-feed', limit, postIndexRowsRead: result.publicRowsRead + result.recipientRowsRead, publicRowsRead: result.publicRowsRead, recipientRowsRead: result.recipientRowsRead, relationshipIndexReads: result.relationshipIndexReads, returned: result.visible.length, eventHistoryScans: 0, storiesScanned: 0, branchesScanned: 0, writes: 0 }); return Object.freeze({ items: Object.freeze(result.visible), nextCursor: result.visible.length === limit ? result.visible.at(-1).reverseSequence + 1 : null }); }
  async listComments({ scope: inputScope, viewerAccountId, postId, parentCommentId = null, limit = 20, cursor = 0 }) { const scope = requireEventScope(inputScope); const post = await this.getPost({ scope, postId }); if (!post || !socialAudiencePermits(post.audience, viewerAccountId) || await this.#isBlocked(scope, post.authorAccountId, viewerAccountId)) return Object.freeze({ items: Object.freeze([]), nextCursor: null }); const parentKey = parentCommentId || 'root'; const rows = await this.#unit.readonly({ stores: ['socialComments'], scope }, repositories => repositories.socialComments.listByIndexRange('by_scope_post_parent_sequence', { lower: [scope.storyId, scope.branchId, postId, parentKey, Number(cursor || 0)], upper: [scope.storyId, scope.branchId, postId, parentKey, MAX_SEQUENCE] }, { limit })); this.#metrics = Object.freeze({ operation: 'list-comments', commentIndexRowsRead: rows.length, eventHistoryScans: 0, storiesScanned: 0, branchesScanned: 0, writes: 0 }); return Object.freeze({ items: Object.freeze(rows), nextCursor: rows.length === limit ? rows.at(-1).sourceEventSequence + 1 : null }); }
  async listEngagements({ scope: inputScope, targetId, kind = ENGAGEMENT_KIND.LIKE, limit = 100 }) { const scope = requireEventScope(inputScope); const rows = await this.#unit.readonly({ stores: ['socialEngagements'], scope }, repositories => repositories.socialEngagements.listByIndex('by_scope_target_kind', [scope.storyId, scope.branchId, targetId, kind, 'active'])); return Object.freeze(rows.slice(0, limit)); }

  async forkFromSnapshot({ parentScope: parentInput, childScope: childInput, instanceIdMap, accountIdMap, deviceIdMap, sourceAuthority = 'tmrw-social-branch-fork', idempotencyKey = 'social-branch-fork' }) { const parentScope = requireEventScope(parentInput); const childScope = requireEventScope(childInput); if (parentScope.storyId !== childScope.storyId) throw new Error('Social fork must remain inside one Story'); const relation = await this.#unit.readonly({ stores: ['branches'], privileged: true }, async repositories => ({ parent: await repositories.branches.get(parentScope.branchId), child: await repositories.branches.get(childScope.branchId) })); if (!relation.parent || !relation.child || relation.child.parentBranchId !== relation.parent.id) throw new Error('Social fork destination is not a direct child Branch'); const snapshot = await this.#unit.readonly({ stores: ['socialPersonas', 'socialGraphEdges', 'socialPosts', 'socialComments', 'socialEngagements'], scope: parentScope }, async repositories => ({ personas: await repositories.socialPersonas.list(), graph: await repositories.socialGraphEdges.list(), posts: await repositories.socialPosts.listByIndexRange('by_scope_current_reverse_sequence', { lower: [parentScope.storyId, parentScope.branchId, 'current', 0], upper: [parentScope.storyId, parentScope.branchId, 'current', MAX_SEQUENCE] }), comments: await repositories.socialComments.list(), engagements: await repositories.socialEngagements.list() })); const source = suffix => ({ authority: sourceAuthority, kind: 'branch-snapshot', recordId: `${parentScope.branchId}:${suffix}`, version: '1' }); const counts = { personas: 0, graph: 0, posts: 0, comments: 0, engagements: 0 };
    for (const persona of snapshot.personas) { if (persona.sourceLevel === 'actor-base') await this.setActorPersona({ scope: childScope, actorId: persona.actorId, persona, source: source(`persona:${persona.personaId}`), idempotencyKey: `${idempotencyKey}:persona:${persona.personaId}` }); else await this.setPersona({ scope: childScope, actorId: persona.actorId, instanceId: instanceIdMap[persona.instanceId], accountId: accountIdMap[persona.accountId], persona, source: source(`persona:${persona.personaId}`), idempotencyKey: `${idempotencyKey}:persona:${persona.personaId}` }); counts.personas += 1; }
    for (const edge of snapshot.graph) { await this.setGraphEdge({ scope: childScope, ownerAccountId: accountIdMap[edge.ownerAccountId], targetAccountId: accountIdMap[edge.targetAccountId], relation: edge.relation, active: edge.active, source: source(`edge:${edge.edgeId}`), idempotencyKey: `${idempotencyKey}:edge:${edge.edgeId}` }); counts.graph += 1; }
    const childPosts = new Map(); for (const post of [...snapshot.posts].sort((a, b) => a.sourceEventSequence - b.sourceEventSequence)) { const result = await this.createPost({ scope: childScope, authorAccountId: accountIdMap[post.authorAccountId], actualAuthorActorId: post.actualAuthorActorId, actualAuthorInstanceId: instanceIdMap[post.actualAuthorInstanceId], deviceId: deviceIdMap[post.deviceId], text: post.text, assetRefs: post.assetRefs, audience: { ...post.audience, recipientAccountIds: post.audience.recipientAccountIds.map(id => accountIdMap[id]) }, source: source(`post:${post.postId}`), idempotencyKey: `${idempotencyKey}:post:${post.postId}` }); childPosts.set(post.postId, result.post.postId); counts.posts += 1; }
    const childComments = new Map(); for (const comment of [...snapshot.comments].sort((a, b) => a.sourceEventSequence - b.sourceEventSequence)) { const result = await this.createComment({ scope: childScope, postId: childPosts.get(comment.postId), parentCommentId: comment.parentCommentId ? childComments.get(comment.parentCommentId) : null, authorAccountId: accountIdMap[comment.authorAccountId], actualAuthorActorId: comment.actualAuthorActorId, actualAuthorInstanceId: instanceIdMap[comment.actualAuthorInstanceId], deviceId: deviceIdMap[comment.deviceId], text: comment.text, source: source(`comment:${comment.commentId}`), idempotencyKey: `${idempotencyKey}:comment:${comment.commentId}` }); childComments.set(comment.commentId, result.comment.commentId); counts.comments += 1; }
    for (const engagement of snapshot.engagements.filter(row => row.active)) { await this.setEngagement({ scope: childScope, targetId: engagement.targetKind === 'post' ? childPosts.get(engagement.targetId) : childComments.get(engagement.targetId), targetKind: engagement.targetKind, kind: engagement.kind, actorAccountId: accountIdMap[engagement.actorAccountId], actualActorId: engagement.actualActorId, actualInstanceId: instanceIdMap[engagement.actualInstanceId], active: true, quoteText: engagement.quoteText, source: source(`engagement:${engagement.engagementId}`), idempotencyKey: `${idempotencyKey}:engagement:${engagement.engagementId}` }); counts.engagements += 1; }
    return Object.freeze({ inheritedFrom: parentScope, childScope, counts: Object.freeze(counts), replaySafe: true }); }
}
