import test from 'node:test';
import assert from 'node:assert/strict';
import { PhoneShellViewModels } from '../../ui/view-models.mjs';
import { TmrwPhoneShell } from '../../ui/shell.mjs';
import { setupPhoneWorldFoundation, ownedInput, utilitySource } from './phone-world-foundation-fixtures.mjs';

const settle = () => new Promise(resolve => setImmediate(resolve));
async function waitFor(predicate) { for (let index = 0; index < 160; index += 1) { if (await predicate()) return; await settle(); } throw new Error('Notes/Search UI did not settle'); }
function find(node, predicate) { if (predicate(node)) return node; for (const child of node?.children || []) { const hit = find(child, predicate); if (hit) return hit; } return null; }
function allText(node, out = []) { if (node?.textContent) out.push(String(node.textContent)); for (const child of node?.children || []) allText(child, out); return out.join(' '); }
function fire(node, type) { for (const listener of node?.listeners?.get?.(type) || []) listener({ currentTarget: node, target: node }); }
function action(c, person, recordId, key, extra = {}) { return { scope: c.scope, ...ownedInput(person), recordId, source: utilitySource(key), producer: 'phase23-notes-search-ui', idempotencyKey: key, ...extra }; }

function wrappedPhoneWorld(real, overrides = {}) {
  const names = ['listNotes', 'listFiles', 'listGallery', 'listCalendar', 'listShopItems', 'listSearch', 'saveNote', 'deleteNote', 'recordSearch', 'clearSearchEntry']; const out = {};
  for (const name of names) out[name] = overrides[name] || (input => real[name](input)); return out;
}
async function setupPersonalUi(manifestId, overrides = null) {
  const c = await setupPhoneWorldFoundation({ castSize: 2, manifestId }); const phoneWorldService = overrides ? wrappedPhoneWorld(c.phoneWorld, overrides(c.phoneWorld)) : c.phoneWorld;
  const viewModels = new PhoneShellViewModels({ database: c.database, phoneStateService: c.phones, contactService: c.contacts, settingsService: c.settings, messageService: c.messages, callService: c.calls, socialService: c.social, insungramService: c.insungram, liveService: c.live, notificationService: c.notifications, phoneWorldService });
  return { ...c, viewModels };
}
function shellFor(c) { return new TmrwPhoneShell({ document: c.document, viewModels: c.viewModels, controller: c.controller, messageService: c.messages, callService: c.calls, callCoordinator: c.viewModels.callCoordinator, socialService: c.social, notificationService: c.notifications, scope: c.scope, playerActorId: c.user.actorId, playerInstanceId: c.user.instanceId, selectedDeviceId: c.user.deviceId }); }
async function open(shell, route) { const button = find(shell.root, node => node.dataset?.route === route); assert.ok(button, `missing ${route}`); button.click(); await settle(); return shell.root.children[3].children[0]; }

test('C2-7 Notes shell shows loading, truthful empty state, and real Back', async () => {
  let release;
  const c = await setupPersonalUi('p23-notes-loading', real => ({ listNotes: input => new Promise((resolve, reject) => { release = () => real.listNotes(input).then(resolve, reject); }) })); const shell = shellFor(c); await shell.mount(c.target); const button = find(shell.root, node => node.dataset?.route === 'notes'); assert.ok(button); button.click(); await waitFor(() => /Loading Notes/.test(allText(shell.root))); release(); await waitFor(() => /No private notes/.test(allText(shell.root))); const panel = shell.root.children[3].children[0]; const back = find(panel, node => node.dataset?.navAction === 'back'); assert.ok(back); back.click(); await settle(); assert.equal(shell.root.children[2].hidden, false);
});

test('C2-7 Notes create/open/edit are canonical one-shot actions and do not grant NPC Knowledge', async () => {
  const c = await setupPersonalUi('p23-notes-create-edit'); const shell = shellFor(c); await shell.mount(c.target); let panel = await open(shell, 'notes'); const knowledgeBefore = await c.database.transaction(['knowledgeGrants'], 'readonly', tx => tx.store('knowledgeGrants').count()); find(panel, node => node.dataset?.noteAction === 'new').click(); await settle(); panel = shell.root.children[3].children[0]; const title = find(panel, node => node.attributes?.get?.('aria-label') === 'Note title'); const body = find(panel, node => node.attributes?.get?.('aria-label') === 'Note text'); title.value = 'Private plan'; body.value = 'Meet at the blue door'; fire(title, 'input'); const save = find(panel, node => node.dataset?.noteAction === 'save'); save.click(); save.click(); await waitFor(async () => (await c.phoneWorld.listNotes({ scope: c.scope, deviceId: c.user.deviceId })).length === 1); let notes = await c.phoneWorld.listNotes({ scope: c.scope, deviceId: c.user.deviceId }); assert.equal(notes[0].title, 'Private plan'); assert.equal(notes[0].text, 'Meet at the blue door'); assert.equal(await c.database.transaction(['knowledgeGrants'], 'readonly', tx => tx.store('knowledgeGrants').count()), knowledgeBefore);
  panel = shell.root.children[3].children[0]; find(panel, node => node.dataset?.noteRecordId === notes[0].recordId).click(); await settle(); panel = shell.root.children[3].children[0]; assert.match(allText(panel), /Meet at the blue door/); find(panel, node => node.dataset?.noteAction === 'edit').click(); await settle(); panel = shell.root.children[3].children[0]; const editBody = find(panel, node => node.attributes?.get?.('aria-label') === 'Note text'); editBody.value = 'Meet at the red door'; fire(editBody, 'input'); find(panel, node => node.dataset?.noteAction === 'save').click(); await waitFor(async () => (await c.phoneWorld.listNotes({ scope: c.scope, deviceId: c.user.deviceId }))[0]?.text === 'Meet at the red door'); notes = await c.phoneWorld.listNotes({ scope: c.scope, deviceId: c.user.deviceId }); assert.equal(notes.length, 1); assert.equal(notes[0].text, 'Meet at the red door');
});

test('C2-7 Notes delete is cancellable, one-shot, and preserves immutable Event history', async () => {
  const c = await setupPersonalUi('p23-notes-delete'); await c.phoneWorld.saveNote(action(c, c.user, 'note-delete', 'note-delete-seed', { title: 'Delete me', text: 'private', sourceKind: 'explicit-user' })); const shell = shellFor(c); await shell.mount(c.target); let panel = await open(shell, 'notes'); find(panel, node => node.dataset?.noteRecordId === 'note-delete').click(); await settle(); panel = shell.root.children[3].children[0]; const before = (await c.utilityEngine.listEvents(c.scope)).length; find(panel, node => node.dataset?.noteAction === 'request-delete').click(); await settle(); panel = shell.root.children[3].children[0]; find(panel, node => node.dataset?.noteAction === 'cancel-delete').click(); await settle(); assert.equal((await c.utilityEngine.listEvents(c.scope)).length, before); assert.equal((await c.phoneWorld.listNotes({ scope: c.scope, deviceId: c.user.deviceId })).length, 1);
  panel = shell.root.children[3].children[0]; find(panel, node => node.dataset?.noteAction === 'request-delete').click(); await settle(); panel = shell.root.children[3].children[0]; const confirm = find(panel, node => node.dataset?.noteAction === 'confirm-delete'); confirm.click(); confirm.click(); await waitFor(async () => (await c.phoneWorld.listNotes({ scope: c.scope, deviceId: c.user.deviceId })).length === 0); assert.equal((await c.utilityEngine.listEvents(c.scope)).length, before + 1); assert.ok((await c.utilityEngine.listEvents(c.scope)).some(event => event.eventType === 'notes.note-state.v1'));
});

test('C2-7 Notes device switch clears selected/form state and unauthorized Their Phone never reveals prior note', async () => {
  const c = await setupPersonalUi('p23-notes-switch'); await c.phoneWorld.saveNote(action(c, c.user, 'note-user', 'note-user-switch', { title: 'USER SECRET NOTE', text: 'hidden', sourceKind: 'explicit-user' })); await c.phoneWorld.saveNote(action(c, c.alice, 'note-alice', 'note-alice-switch', { title: 'ALICE NOTE', text: 'alice', sourceKind: 'explicit-user' })); const shell = shellFor(c); await shell.mount(c.target); let panel = await open(shell, 'notes'); find(panel, node => node.dataset?.noteRecordId === 'note-user').click(); await settle(); assert.match(allText(shell.root), /USER SECRET NOTE/); await shell.selectDevice(c.alice.deviceId); assert.match(allText(shell.root), /Notes are unavailable until access to this phone is granted/); assert.doesNotMatch(allText(shell.root), /USER SECRET NOTE|ALICE NOTE/); await shell.selectDevice(c.user.deviceId); panel = shell.root.children[3].children[0]; assert.equal(find(panel, node => node.dataset?.noteDetailsId), null);
});

test('C2-7 Notes read failure is recoverable and exposes no stale write controls', async () => {
  const c = await setupPersonalUi('p23-notes-error', () => ({ listNotes: async () => { throw new Error('Injected Notes read failure'); } })); const shell = shellFor(c); await shell.mount(c.target); const panel = await open(shell, 'notes'); assert.match(allText(panel), /Notes error: Injected Notes read failure/); assert.equal(find(panel, node => node.dataset?.noteAction === 'new'), null); assert.equal(find(panel, node => node.attributes?.get?.('role') === 'status'), null);
});

test('C2-7 Search shell loading/empty-query state and Back are truthful', async () => {
  let release;
  const c = await setupPersonalUi('p23-search-loading', real => ({ listSearch: input => new Promise((resolve, reject) => { release = () => real.listSearch(input).then(resolve, reject); }) })); const shell = shellFor(c); await shell.mount(c.target); const button = find(shell.root, node => node.dataset?.route === 'search'); assert.ok(button); button.click(); await waitFor(() => /Loading Search/.test(allText(shell.root))); release(); await waitFor(() => /Enter a query to search local phone-world content/.test(allText(shell.root))); const panel = shell.root.children[3].children[0]; assert.match(allText(panel), /does not fabricate internet results or a Discover feed/i); assert.equal(find(panel, node => node.dataset?.searchAction === 'submit').disabled, true); assert.ok(find(panel, node => node.dataset?.navAction === 'back'));
});

test('C2-7 Search submit writes one canonical history record, returns local results, and clear-history is one-shot', async () => {
  const c = await setupPersonalUi('p23-search-submit'); await c.phoneWorld.saveNote(action(c, c.user, 'note-blue', 'note-blue', { title: 'Blue door plan', text: 'meet tonight', sourceKind: 'explicit-user' })); await c.phoneWorld.saveFile(action(c, c.user, 'file-red', 'file-red', { name: 'red.txt', fileKind: 'text', contentText: 'red only', sourceKind: 'explicit-user' })); const shell = shellFor(c); await shell.mount(c.target); let panel = await open(shell, 'search'); const input = find(panel, node => node.attributes?.get?.('aria-label') === 'Search this phone'); input.value = 'blue'; fire(input, 'input'); const submit = find(panel, node => node.dataset?.searchAction === 'submit'); submit.click(); submit.click(); await waitFor(async () => (await c.phoneWorld.listSearch({ scope: c.scope, deviceId: c.user.deviceId })).length === 1); panel = shell.root.children[3].children[0]; assert.match(allText(panel), /Blue door plan/); assert.doesNotMatch(allText(panel), /red\.txt/); let history = await c.phoneWorld.listSearch({ scope: c.scope, deviceId: c.user.deviceId }); assert.equal(history.length, 1); assert.equal(history[0].provider, 'local-phone-world'); const clear = find(panel, node => node.dataset?.searchAction === 'clear-history'); clear.click(); clear.click(); await waitFor(async () => (await c.phoneWorld.listSearch({ scope: c.scope, deviceId: c.user.deviceId })).length === 0); history = await c.phoneWorld.listSearch({ scope: c.scope, deviceId: c.user.deviceId }); assert.equal(history.length, 0); assert.match(allText(shell.root), /No search history/);
});

test('C2-7 Search no-result/error/device-switch paths remain local, recoverable, and privacy-safe', async () => {
  const c = await setupPersonalUi('p23-search-privacy'); await c.phoneWorld.saveNote(action(c, c.user, 'note-private', 'note-private-search', { title: 'USER SEARCH SECRET', text: 'hidden', sourceKind: 'explicit-user' })); const shell = shellFor(c); await shell.mount(c.target); let panel = await open(shell, 'search'); let input = find(panel, node => node.attributes?.get?.('aria-label') === 'Search this phone'); input.value = 'absent'; fire(input, 'input'); find(panel, node => node.dataset?.searchAction === 'submit').click(); await waitFor(() => /No local results found/.test(allText(shell.root))); await shell.selectDevice(c.alice.deviceId); assert.match(allText(shell.root), /Search is unavailable until access to this phone is granted/); assert.doesNotMatch(allText(shell.root), /USER SEARCH SECRET|absent/);
  const failed = await setupPersonalUi('p23-search-error', () => ({ listSearch: async () => { throw new Error('Injected Search read failure'); } })); const failedShell = shellFor(failed); await failedShell.mount(failed.target); panel = await open(failedShell, 'search'); assert.match(allText(panel), /Search error: Injected Search read failure/); assert.equal(find(panel, node => node.dataset?.searchAction === 'submit'), null); assert.equal(find(panel, node => node.attributes?.get?.('role') === 'status'), null);
});
