import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs/promises';
import { TmrwPhoneShell } from '../../ui/shell.mjs';
import { PhoneShellViewModels } from '../../ui/view-models.mjs';
import { GUIDE_TOPICS, GUIDE_TOPIC_CONTENT, GuideStateService } from '../../ui/guide.mjs';
import { EXPERIENCE_PRESET, PHONE_NUMBER_DISCOVERY } from '../../ui/experience-presets.mjs';
import { SOCIAL_AUDIENCE } from '../../domain/social/audience.mjs';
import { setupPhase17 } from '../phase17/notification-fixtures.mjs';
import { postFrom } from '../phase15/social-fixtures.mjs';
import { createDm, sendFrom } from '../phase8/messaging-fixtures.mjs';
import { startLive, joinLive, liveMessage } from '../phase16/live-fixtures.mjs';

const settle = () => new Promise(resolve => setImmediate(resolve));
async function waitFor(predicate, label = 'P23-D UI') { for (let index = 0; index < 160; index += 1) { if (await predicate()) return; await settle(); } throw new Error(`${label} did not settle`); }
function find(node, predicate) { if (predicate(node)) return node; for (const child of node?.children || []) { const hit = find(child, predicate); if (hit) return hit; } return null; }
function findAll(node, predicate, out = []) { if (predicate(node)) out.push(node); for (const child of node?.children || []) findAll(child, predicate, out); return out; }
function allText(node, out = []) { if (node?.textContent) out.push(String(node.textContent)); for (const child of node?.children || []) allText(child, out); return out.join(' '); }
function inputValue(node, value) { node.value = value; for (const listener of node.listeners?.get?.('input') || []) listener({ currentTarget: node }); }
function proxyWith(target, overrides = {}) { return new Proxy(target, { get(base, property) { if (Object.prototype.hasOwnProperty.call(overrides, property)) return overrides[property]; const value = base[property]; return typeof value === 'function' ? value.bind(base) : value; } }); }
function modelsFor(c, { settingsService = c.settings, guideService = null, socialService = c.social, insungramService = c.insungram, liveService = c.live } = {}) {
  return new PhoneShellViewModels({ database: c.database, phoneStateService: c.phones, contactService: c.contacts, settingsService, guideService, messageService: c.messages, callService: c.calls, socialService, insungramService, liveService, notificationService: c.notifications });
}
function shellFor(c, viewModels = c.viewModels, socialService = c.social) { return new TmrwPhoneShell({ document: c.document, viewModels, controller: c.controller, messageService: c.messages, callService: c.calls, callCoordinator: viewModels.callCoordinator, socialService, notificationService: c.notifications, scope: c.scope, playerActorId: c.user.actorId, playerInstanceId: c.user.instanceId, selectedDeviceId: c.user.deviceId }); }
async function open(shell, route) { const button = find(shell.root, node => node.dataset?.route === route); assert.ok(button, `missing ${route}`); button.click(); await waitFor(() => shell.metrics.router === route && shell.root.children[3]?.children?.[0]?.dataset?.route === route && !new RegExp(`Loading ${route}`, 'i').test(allText(shell.root.children[3])), `open ${route}`); return shell.root.children[3].children[0]; }
async function back(shell, panel) { const button = find(panel, node => node.dataset?.navAction === 'back'); assert.ok(button); assert.equal(button.attributes.get('aria-label'), 'Back'); button.click(); await waitFor(() => shell.metrics.router === 'launcher', 'Back'); }

// GUIDE — 4 focused cases.
test('P23-D Guide shows deterministic real topics, loading, current topic, topic content, and Back', async () => {
  const c = await setupPhase17({ manifestId: 'p23d-guide-initial' }); let release; let delayed = true; const guideState = new GuideStateService({ database: c.database });
  const guide = proxyWith(guideState, { get: input => delayed ? new Promise((resolve, reject) => { release = () => { delayed = false; guideState.get(input).then(resolve, reject); }; }) : guideState.get(input) });
  const models = modelsFor(c, { guideService: guide }); const shell = shellFor(c, models); await shell.mount(c.target);
  const launch = find(shell.root, node => node.dataset?.route === 'guide'); launch.click(); await waitFor(() => /Loading Guide/.test(allText(shell.root)), 'Guide loading'); release(); await waitFor(() => /Use My Phone for the player device/.test(allText(shell.root)), 'Guide hydrate');
  const panel = shell.root.children[3].children[0]; const topics = findAll(panel, node => node.dataset?.guideTopic); assert.equal(topics.length, GUIDE_TOPICS.length); assert.ok(topics.every(node => String(node.textContent).trim().length > 0));
  const privacy = topics.find(node => node.dataset.guideTopic === 'Privacy & Character Knowledge'); privacy.click(); await waitFor(() => /Knowledge grants require their own canonical evidence/.test(allText(shell.root)), 'Guide topic');
  assert.equal(find(shell.root, node => node.dataset?.guideTopic === 'Privacy & Character Knowledge').attributes.get('aria-current'), 'true'); assert.equal(GUIDE_TOPIC_CONTENT['Privacy & Character Knowledge'].includes('Knowledge'), true); await back(shell, shell.root.children[3].children[0]);
});

test('P23-D Guide reset/replay use GuideStateService and replay count persists across shell reopen', async () => {
  const c = await setupPhase17({ manifestId: 'p23d-guide-persist' }); const guideState = new GuideStateService({ database: c.database }); const models = modelsFor(c, { guideService: guideState }); let shell = shellFor(c, models); await shell.mount(c.target); let panel = await open(shell, 'guide');
  find(panel, node => node.dataset?.action === 'replay-guide-tutorial').click(); await waitFor(async () => (await guideState.get({ scope: c.scope, playerInstanceId: c.user.instanceId })).tutorialReplayCount === 1, 'Guide replay');
  panel = shell.root.children[3].children[0]; find(panel, node => node.dataset?.action === 'reset-guide-tips').click(); await waitFor(async () => (await guideState.get({ scope: c.scope, playerInstanceId: c.user.instanceId })).dismissedTips.length === 0, 'Guide reset');
  const state = await guideState.get({ scope: c.scope, playerInstanceId: c.user.instanceId }); assert.equal(state.tutorialReplayCount, 1); assert.equal(state.guideStateIsCanon, false);
  shell.dispose(); shell = shellFor(c, models); await shell.mount(c.target); panel = await open(shell, 'guide'); assert.match(allText(panel), /Tutorial replays: 1/); assert.equal(find(panel, node => node.dataset?.guideTopic === GUIDE_TOPICS[0]).attributes.get('aria-current'), 'true');
});

test('P23-D Guide service read/action failures stay app-scoped and recover without fake progress', async () => {
  const c = await setupPhase17({ manifestId: 'p23d-guide-error' }); let failRead = true; let failReplay = true; const guideState = new GuideStateService({ database: c.database });
  const guide = proxyWith(guideState, { get: input => failRead ? Promise.reject(new Error('Injected Guide read failure')) : guideState.get(input), replayTutorial: input => failReplay ? Promise.reject(new Error('Injected Guide replay failure')) : guideState.replayTutorial(input) });
  const shell = shellFor(c, modelsFor(c, { guideService: guide })); await shell.mount(c.target); let panel = await open(shell, 'guide'); assert.match(allText(panel), /Guide could not be loaded: Injected Guide read failure/); assert.equal(find(panel, node => node.dataset?.action === 'replay-guide-tutorial'), null); assert.ok(find(panel, node => node.dataset?.action === 'retry-guide'));
  failRead = false; find(panel, node => node.dataset?.action === 'retry-guide').click(); await waitFor(() => /Topics/.test(allText(shell.root)), 'Guide retry'); panel = shell.root.children[3].children[0]; find(panel, node => node.dataset?.action === 'replay-guide-tutorial').click(); await waitFor(() => /Injected Guide replay failure/.test(allText(shell.root)), 'Guide action failure');
  assert.equal((await guideState.get({ scope: c.scope, playerInstanceId: c.user.instanceId })).tutorialReplayCount, 0); failReplay = false; find(shell.root, node => node.dataset?.action === 'retry-guide').click(); await waitFor(() => /Replay tutorial/.test(allText(shell.root)), 'Guide second recovery');
});

test('P23-D Guide state is player/Story scoped and does not become Their Phone private app data', async () => {
  const c = await setupPhase17({ castSize: 2, manifestId: 'p23d-guide-scope' }); const guideState = new GuideStateService({ database: c.database }); await guideState.replayTutorial({ scope: c.scope, playerInstanceId: c.user.instanceId }); const shell = shellFor(c, modelsFor(c, { guideService: guideState })); await shell.mount(c.target); await open(shell, 'guide'); assert.match(allText(shell.root), /Tutorial replays: 1/); await shell.selectDevice(c.alice.deviceId); assert.match(allText(shell.root), /Tutorial replays: 1/); assert.match(allText(shell.root), /Guide state is player UI state, not story canon/);
});

// SETTINGS — 4 focused cases.
test('P23-D Settings renders only real backed options, truthful Voice-unavailable state, and Back', async () => {
  const c = await setupPhase17({ manifestId: 'p23d-settings-render' }); const shell = shellFor(c); await shell.mount(c.target); const panel = await open(shell, 'settings');
  for (const setting of ['preset-simple', 'preset-story', 'preset-immersive', 'number-discovery-smart', 'number-discovery-on', 'number-discovery-off', 'developer-diagnostics', 'continue-story-after-calls']) assert.ok(find(panel, node => node.dataset?.setting === setting), setting);
  assert.match(allText(panel), /Text Calls ready/); assert.match(allText(panel), /Voice runtime unavailable|no Voice runtime/i); const testVoice = find(panel, node => node.dataset?.voiceAction === 'test-voice'); assert.ok(testVoice); assert.equal(testVoice.disabled, true); assert.doesNotMatch(allText(panel), /Social AI enabled|Live AI enabled|provider API key/i); await back(shell, panel);
});

test('P23-D supported Settings updates persist and a reopened shell reflects the stored values', async () => {
  const c = await setupPhase17({ manifestId: 'p23d-settings-persist' }); let shell = shellFor(c); await shell.mount(c.target); let panel = await open(shell, 'settings');
  find(panel, node => node.dataset?.setting === 'preset-immersive').click(); await waitFor(async () => (await c.settings.get({ scope: c.scope, playerInstanceId: c.user.instanceId })).preset === EXPERIENCE_PRESET.IMMERSIVE, 'preset persist'); panel = shell.root.children[3].children[0];
  find(panel, node => node.dataset?.setting === 'number-discovery-off').click(); await waitFor(async () => (await c.settings.get({ scope: c.scope, playerInstanceId: c.user.instanceId })).phoneNumberDiscovery === PHONE_NUMBER_DISCOVERY.OFF, 'discovery persist'); panel = shell.root.children[3].children[0];
  find(panel, node => node.dataset?.setting === 'continue-story-after-calls').click(); await waitFor(async () => (await c.settings.get({ scope: c.scope, playerInstanceId: c.user.instanceId })).continueStoryAfterCalls === true, 'call setting persist');
  shell.dispose(); shell = shellFor(c); await shell.mount(c.target); panel = await open(shell, 'settings'); assert.equal(find(panel, node => node.dataset?.setting === 'number-discovery-off').attributes.get('aria-pressed'), 'true'); assert.match(allText(panel), /Continue story after calls: On/);
});

test('P23-D Settings uses the real developer Diagnostics enable/disable preference and gate path', async () => {
  const c = await setupPhase17({ manifestId: 'p23d-settings-diagnostics' }); const shell = shellFor(c); await shell.mount(c.target); assert.equal(find(shell.root, node => node.dataset?.route === 'diagnostics'), null); let panel = await open(shell, 'settings'); assert.equal(find(panel, node => node.dataset?.action === 'open-diagnostics'), null);
  find(panel, node => node.dataset?.setting === 'developer-diagnostics').click(); await waitFor(async () => (await c.settings.get({ scope: c.scope, playerInstanceId: c.user.instanceId })).developerDiagnosticsEnabled === true, 'Diagnostics enable'); panel = shell.root.children[3].children[0]; const openDiagnostics = find(panel, node => node.dataset?.action === 'open-diagnostics'); assert.ok(openDiagnostics); openDiagnostics.click(); await waitFor(() => shell.metrics.router === 'diagnostics' && /Read-only bounded runtime diagnostics/.test(allText(shell.root)), 'Diagnostics open');
  await back(shell, shell.root.children[3].children[0]); assert.ok(find(shell.root, node => node.dataset?.route === 'diagnostics')); panel = await open(shell, 'settings'); find(panel, node => node.dataset?.setting === 'developer-diagnostics').click(); await waitFor(async () => (await c.settings.get({ scope: c.scope, playerInstanceId: c.user.instanceId })).developerDiagnosticsEnabled === false, 'Diagnostics disable'); await back(shell, shell.root.children[3].children[0]); assert.equal(find(shell.root, node => node.dataset?.route === 'diagnostics'), null);
});

test('P23-D Settings read/update failures remain recoverable inside the Phone shell', async () => {
  const c = await setupPhase17({ manifestId: 'p23d-settings-error' }); let failRead = false; let failUpdate = true;
  const settings = proxyWith(c.settings, { get: input => failRead ? Promise.reject(new Error('Injected Settings read failure')) : c.settings.get(input), setDeveloperDiagnostics: input => failUpdate ? Promise.reject(new Error('Injected Settings update failure')) : c.settings.setDeveloperDiagnostics(input) });
  const shell = shellFor(c, modelsFor(c, { settingsService: settings })); await shell.mount(c.target); failRead = true; find(shell.root, node => node.dataset?.route === 'settings').click(); await waitFor(() => /Settings is unavailable: Injected Settings read failure/.test(allText(shell.root)), 'Settings read error'); assert.ok(find(shell.root, node => node.dataset?.action === 'retry-app'));
  failRead = false; find(shell.root, node => node.dataset?.action === 'retry-app').click(); await waitFor(() => /Developer Diagnostics/.test(allText(shell.root)), 'Settings read recovery'); let panel = shell.root.children[3].children[0]; find(panel, node => node.dataset?.setting === 'developer-diagnostics').click(); await waitFor(() => /Settings update failed: Injected Settings update failure/.test(allText(shell.root)), 'Settings update error'); assert.equal((await c.settings.get({ scope: c.scope, playerInstanceId: c.user.instanceId })).developerDiagnosticsEnabled, false);
  failUpdate = false; panel = shell.root.children[3].children[0]; find(panel, node => node.dataset?.setting === 'developer-diagnostics').click(); await waitFor(async () => (await c.settings.get({ scope: c.scope, playerInstanceId: c.user.instanceId })).developerDiagnosticsEnabled === true, 'Settings update recovery');
});

// DIAGNOSTICS — 1 focused case.
test('P23-D Diagnostics is hidden by default, read-only/truthful when enabled, credential-safe, access-gated, and has Back', async () => {
  const c = await setupPhase17({ castSize: 2, manifestId: 'p23d-diagnostics' }); const shell = shellFor(c); await shell.mount(c.target); assert.equal(find(shell.root, node => node.dataset?.route === 'diagnostics'), null); await c.settings.setDeveloperDiagnostics({ scope: c.scope, playerInstanceId: c.user.instanceId, enabled: true }); await shell.renderActive(); const panel = await open(shell, 'diagnostics'); const pre = find(panel, node => node.tagName === 'pre'); assert.ok(pre); assert.match(pre.textContent, /"activeTimers"|"selectedPhoneReads"/); assert.doesNotMatch(pre.textContent, /api.?key|credential|password|bearer|secret|token/i); assert.match(allText(panel), /Read-only bounded runtime diagnostics/);
  await shell.selectDevice(c.alice.deviceId); assert.match(allText(shell.root), /Diagnostics are unavailable for this phone perspective until access is granted/); assert.equal(find(shell.root, node => node.tagName === 'pre'), null); await back(shell, shell.root.children[3].children[0]);
});

// FEED — 4 focused cases.
test('P23-D Feed exposes loading, truthful empty/manual-only state, and Back', async () => {
  const c = await setupPhase17({ manifestId: 'p23d-feed-loading' }); let release; const social = proxyWith(c.social, { listFeed: input => new Promise((resolve, reject) => { release = () => c.social.listFeed(input).then(resolve, reject); }) }); const shell = shellFor(c, modelsFor(c, { socialService: social }), social); await shell.mount(c.target); find(shell.root, node => node.dataset?.route === 'feed').click(); await waitFor(() => /Loading Feed/.test(allText(shell.root)), 'Feed loading'); release(); await waitFor(() => /No canonical posts yet/.test(allText(shell.root)), 'Feed empty'); const panel = shell.root.children[3].children[0]; assert.match(allText(panel), /Manual canonical posts only/); assert.match(allText(panel), /Autonomous Social generation is disabled/); await back(shell, panel);
});

test('P23-D Feed renders canonical posts and manual Post is one-shot under double click', async () => {
  const c = await setupPhase17({ manifestId: 'p23d-feed-one-shot' }); let createCalls = 0; let release; const social = proxyWith(c.social, { createPost: input => { createCalls += 1; return new Promise((resolve, reject) => { release = () => c.social.createPost(input).then(resolve, reject); }); } }); const shell = shellFor(c, modelsFor(c, { socialService: social }), social); await shell.mount(c.target); let panel = await open(shell, 'feed'); const textarea = find(panel, node => node.tagName === 'textarea'); const post = find(panel, node => node.dataset?.action === 'create-feed-post'); inputValue(textarea, 'ONE SHOT CANONICAL POST'); assert.equal(post.disabled, false); post.click(); post.click(); assert.equal(createCalls, 1); release(); await waitFor(() => /ONE SHOT CANONICAL POST/.test(allText(shell.root)), 'Feed post'); assert.equal((await c.social.listFeed({ scope: c.scope, viewerAccountId: c.user.accountId })).items.length, 1);
});

test('P23-D Feed read failure is explicit/recoverable and never leaves write controls active', async () => {
  const c = await setupPhase17({ manifestId: 'p23d-feed-error' }); let fail = true; const social = proxyWith(c.social, { listFeed: input => fail ? Promise.reject(new Error('Injected Feed read failure')) : c.social.listFeed(input) }); const shell = shellFor(c, modelsFor(c, { socialService: social }), social); await shell.mount(c.target); let panel = await open(shell, 'feed'); assert.match(allText(panel), /Feed could not be loaded: Injected Feed read failure/); assert.equal(find(panel, node => node.dataset?.action === 'create-feed-post'), null); assert.doesNotMatch(allText(panel), /No canonical posts yet/); fail = false; find(panel, node => node.dataset?.action === 'retry-feed').click(); await waitFor(() => /No canonical posts yet/.test(allText(shell.root)), 'Feed recovery'); assert.ok(find(shell.root, node => node.dataset?.action === 'create-feed-post'));
});

test('P23-D Feed clears stale account data on authorized switch and reveals nothing on unauthorized Their Phone', async () => {
  const c = await setupPhase17({ castSize: 2, manifestId: 'p23d-feed-switch' }); await postFrom(c, c.user, { key: 'p23d-user-feed', text: 'USER PRIVATE FEED', audience: { kind: SOCIAL_AUDIENCE.SELECTED, recipientAccountIds: [c.user.accountId] } }); await postFrom(c, c.alice, { key: 'p23d-alice-feed', text: 'ALICE PRIVATE FEED', audience: { kind: SOCIAL_AUDIENCE.SELECTED, recipientAccountIds: [c.alice.accountId] } }); await c.overrides.grant({ scope: c.scope, deviceId: c.alice.deviceId, action: 'inspect', playerActorId: c.user.actorId, playerInstanceId: c.user.instanceId }); let releaseAlice; const social = proxyWith(c.social, { listFeed: input => input.viewerAccountId === c.alice.accountId && !releaseAlice ? new Promise((resolve, reject) => { releaseAlice = () => c.social.listFeed(input).then(resolve, reject); }) : c.social.listFeed(input) }); const shell = shellFor(c, modelsFor(c, { socialService: social }), social); await shell.mount(c.target); await open(shell, 'feed'); assert.match(allText(shell.root), /USER PRIVATE FEED/); const switching = shell.selectDevice(c.alice.deviceId); await waitFor(() => /Loading Feed/.test(allText(shell.root)), 'Feed switch loading'); assert.doesNotMatch(allText(shell.root), /USER PRIVATE FEED/); releaseAlice(); await switching; assert.match(allText(shell.root), /ALICE PRIVATE FEED/); assert.doesNotMatch(allText(shell.root), /USER PRIVATE FEED/); await c.overrides.clear({ scope: c.scope, deviceId: c.alice.deviceId, action: 'inspect' }); await shell.selectDevice(c.user.deviceId); await shell.selectDevice(c.alice.deviceId); assert.match(allText(shell.root), /Feed is unavailable until access is granted/); assert.doesNotMatch(allText(shell.root), /USER PRIVATE FEED|ALICE PRIVATE FEED/);
});

// INSUNGRAM — 3 focused cases.
test('P23-D Insungram exposes loading, truthful empty/read-only state, and Back', async () => {
  const c = await setupPhase17({ manifestId: 'p23d-insungram-loading' }); let release; const insungram = proxyWith(c.insungram, { conversations: input => new Promise((resolve, reject) => { release = () => c.insungram.conversations(input).then(resolve, reject); }) }); const shell = shellFor(c, modelsFor(c, { insungramService: insungram })); await shell.mount(c.target); find(shell.root, node => node.dataset?.route === 'insungram').click(); await waitFor(() => /Loading Insungram/.test(allText(shell.root)), 'Insungram loading'); release(); await waitFor(() => /No canonical conversations/.test(allText(shell.root)), 'Insungram empty'); const panel = shell.root.children[3].children[0]; assert.match(allText(panel), /Read-only view of existing canonical conversations/); assert.match(allText(panel), /Autonomous Social generation is disabled/); await back(shell, panel);
});

test('P23-D Insungram renders existing canonical conversations and recovers from scoped read failure', async () => {
  const c = await setupPhase17({ manifestId: 'p23d-insungram-content-error' }); const dm = await createDm(c); await sendFrom(c, { threadId: dm.thread.threadId, key: 'p23d-ins-msg', text: 'CANONICAL DM CONTENT' }); let fail = false; const insungram = proxyWith(c.insungram, { conversations: input => fail ? Promise.reject(new Error('Injected Insungram read failure')) : c.insungram.conversations(input) }); const shell = shellFor(c, modelsFor(c, { insungramService: insungram })); await shell.mount(c.target); let panel = await open(shell, 'insungram'); const row = find(panel, node => node.dataset?.threadId === dm.thread.threadId); assert.ok(row); assert.equal(row.tagName, 'li'); assert.match(allText(panel), /Private conversation/); fail = true; await shell.renderActive(); panel = shell.root.children[3].children[0]; assert.match(allText(panel), /Insungram could not be loaded: Injected Insungram read failure/); assert.equal(find(panel, node => node.dataset?.threadId), null); fail = false; find(panel, node => node.dataset?.action === 'retry-insungram').click(); await waitFor(() => /Private conversation/.test(allText(shell.root)), 'Insungram recovery');
});

test('P23-D Insungram clears stale conversation presentation on switch and respects Their Phone access', async () => {
  const c = await setupPhase17({ castSize: 2, manifestId: 'p23d-insungram-switch' }); const dm = await createDm(c); await sendFrom(c, { threadId: dm.thread.threadId, key: 'p23d-ins-switch-msg', text: 'PRIVATE CONVERSATION' }); await c.overrides.grant({ scope: c.scope, deviceId: c.alice.deviceId, action: 'inspect', playerActorId: c.user.actorId, playerInstanceId: c.user.instanceId }); let releaseAlice; const insungram = proxyWith(c.insungram, { conversations: input => input.viewerAccountId === c.alice.accountId && !releaseAlice ? new Promise((resolve, reject) => { releaseAlice = () => c.insungram.conversations(input).then(resolve, reject); }) : c.insungram.conversations(input) }); const shell = shellFor(c, modelsFor(c, { insungramService: insungram })); await shell.mount(c.target); await open(shell, 'insungram'); assert.match(allText(shell.root), /Private conversation/); const switching = shell.selectDevice(c.alice.deviceId); await waitFor(() => /Loading Insungram/.test(allText(shell.root)), 'Insungram switch loading'); assert.doesNotMatch(allText(shell.root), /Private conversation/); releaseAlice(); await switching; assert.match(allText(shell.root), /Private conversation/); await c.overrides.clear({ scope: c.scope, deviceId: c.alice.deviceId, action: 'inspect' }); await shell.selectDevice(c.user.deviceId); await shell.selectDevice(c.alice.deviceId); assert.match(allText(shell.root), /Insungram is unavailable until access is granted/); assert.equal(find(shell.root, node => node.dataset?.threadId), null);
});

// LIVE — 3 focused cases.
test('P23-D Live exposes loading, truthful empty/offline read-only state, and Back', async () => {
  const c = await setupPhase17({ manifestId: 'p23d-live-loading' }); let release; const live = proxyWith(c.live, { listSessions: input => new Promise((resolve, reject) => { release = () => c.live.listSessions(input).then(resolve, reject); }) }); const shell = shellFor(c, modelsFor(c, { liveService: live })); await shell.mount(c.target); find(shell.root, node => node.dataset?.route === 'live').click(); await waitFor(() => /Loading Live/.test(allText(shell.root)), 'Live loading'); release(); await waitFor(() => /No canonical Live sessions/.test(allText(shell.root)), 'Live empty'); const panel = shell.root.children[3].children[0]; assert.match(allText(panel), /Read-only canonical Live state/); assert.match(allText(panel), /Autonomous Live generation is disabled/); await back(shell, panel);
});

test('P23-D Live renders authoritative session/viewer/chat state and recovers from read failure', async () => {
  const c = await setupPhase17({ manifestId: 'p23d-live-content-error' }); const liveSession = await startLive(c, c.user, { key: 'p23d-live-real', title: 'AUTHORITATIVE LIVE SESSION' }); await joinLive(c, liveSession.session.sessionId, c.alice, { key: 'p23d-live-viewer' }); await liveMessage(c, liveSession.session.sessionId, c.user, { key: 'p23d-live-message', text: 'AUTHORITATIVE LIVE CHAT' }); let fail = false; const live = proxyWith(c.live, { listSessions: input => fail ? Promise.reject(new Error('Injected Live read failure')) : c.live.listSessions(input) }); const shell = shellFor(c, modelsFor(c, { liveService: live })); await shell.mount(c.target); let panel = await open(shell, 'live'); assert.match(allText(panel), /AUTHORITATIVE LIVE SESSION/); assert.match(allText(panel), /AUTHORITATIVE LIVE CHAT/); assert.match(allText(panel), /1 viewers/); fail = true; await shell.renderActive(); panel = shell.root.children[3].children[0]; assert.match(allText(panel), /Live could not be loaded: Injected Live read failure/); assert.doesNotMatch(allText(panel), /No canonical Live sessions/); fail = false; find(panel, node => node.dataset?.action === 'retry-live').click(); await waitFor(() => /AUTHORITATIVE LIVE SESSION/.test(allText(shell.root)), 'Live recovery');
});

test('P23-D Live clears stale session state on authorized switch and respects Their Phone access', async () => {
  const c = await setupPhase17({ castSize: 2, manifestId: 'p23d-live-switch' }); await startLive(c, c.user, { key: 'p23d-user-live', title: 'USER PRIVATE LIVE', audience: { kind: SOCIAL_AUDIENCE.SELECTED, recipientAccountIds: [c.user.accountId] } }); await startLive(c, c.alice, { key: 'p23d-alice-live', title: 'ALICE PRIVATE LIVE', audience: { kind: SOCIAL_AUDIENCE.SELECTED, recipientAccountIds: [c.alice.accountId] } }); await c.overrides.grant({ scope: c.scope, deviceId: c.alice.deviceId, action: 'inspect', playerActorId: c.user.actorId, playerInstanceId: c.user.instanceId }); let releaseAlice; const live = proxyWith(c.live, { listSessions: input => input.viewerAccountId === c.alice.accountId && !releaseAlice ? new Promise((resolve, reject) => { releaseAlice = () => c.live.listSessions(input).then(resolve, reject); }) : c.live.listSessions(input) }); const shell = shellFor(c, modelsFor(c, { liveService: live })); await shell.mount(c.target); await open(shell, 'live'); assert.match(allText(shell.root), /USER PRIVATE LIVE/); const switching = shell.selectDevice(c.alice.deviceId); await waitFor(() => /Loading Live/.test(allText(shell.root)), 'Live switch loading'); assert.doesNotMatch(allText(shell.root), /USER PRIVATE LIVE/); releaseAlice(); await switching; assert.match(allText(shell.root), /ALICE PRIVATE LIVE/); assert.doesNotMatch(allText(shell.root), /USER PRIVATE LIVE/); await c.overrides.clear({ scope: c.scope, deviceId: c.alice.deviceId, action: 'inspect' }); await shell.selectDevice(c.user.deviceId); await shell.selectDevice(c.alice.deviceId); assert.match(allText(shell.root), /Live is unavailable until access is granted/); assert.doesNotMatch(allText(shell.root), /USER PRIVATE LIVE|ALICE PRIVATE LIVE/);
});

// AI boundaries + shell/mobile/accessibility — 2 focused cases.
test('P23-D Feed/Insungram/Live navigation, reopen, and error recovery schedule zero autonomous jobs and both boundaries remain disabled', async () => {
  const c = await setupPhase17({ manifestId: 'p23d-ai-boundaries' }); let socialJobs = 0; let liveJobs = 0; c.socialAi.prepare = () => { socialJobs += 1; return { scheduled: false }; }; c.socialAi.schedule = () => { socialJobs += 1; }; c.liveAi.prepare = () => { liveJobs += 1; return { scheduled: false }; }; c.liveAi.schedule = () => { liveJobs += 1; };
  let shell = shellFor(c); await shell.mount(c.target); for (const route of ['feed', 'insungram', 'live']) { const panel = await open(shell, route); await back(shell, panel); }
  shell.dispose(); shell = shellFor(c); await shell.mount(c.target); await open(shell, 'feed'); shell.dispose();
  let fail = true; const social = proxyWith(c.social, { listFeed: input => fail ? Promise.reject(new Error('AI-boundary injected read error')) : c.social.listFeed(input) }); shell = shellFor(c, modelsFor(c, { socialService: social }), social); await shell.mount(c.target); let panel = await open(shell, 'feed'); fail = false; find(panel, node => node.dataset?.action === 'retry-feed').click(); await waitFor(() => /Manual canonical posts only/.test(allText(shell.root)), 'AI error recovery');
  assert.equal(socialJobs, 0); assert.equal(liveJobs, 0); assert.equal(c.socialAi.enabled, false); assert.equal(c.liveAi.enabled, false);
});

test('P23-D router/accessibility/mobile contract covers all P23-D routes at 390x844 without horizontal-overflow-prone controls', async () => {
  const c = await setupPhase17({ manifestId: 'p23d-mobile-accessibility' }); const shell = shellFor(c); await shell.mount(c.target); for (const route of ['guide', 'settings', 'feed', 'insungram', 'live']) assert.ok(find(shell.root, node => node.dataset?.route === route), route); assert.equal(find(shell.root, node => node.dataset?.route === 'diagnostics'), null);
  const guide = await open(shell, 'guide'); assert.ok(findAll(guide, node => node.dataset?.guideTopic).every(node => node.attributes.get('aria-current') != null && String(node.textContent).trim())); await back(shell, guide); const settings = await open(shell, 'settings'); assert.ok(findAll(settings, node => node.dataset?.setting).every(node => String(node.textContent).trim().length > 0)); await back(shell, settings);
  const css = await fs.readFile(new URL('../../ui/styles.css', import.meta.url), 'utf8'); assert.match(css, /width:min\(100%,420px\)/); assert.match(css, /tmrw-v3-app-back\{width:44px;min-width:44px/); assert.match(css, /tmrw-v3-content,.tmrw-v3-panel.*min-width:0;max-width:100%/s); assert.match(css, /tmrw-v3-guide-topic-list.*flex-wrap:wrap/s); assert.match(css, /tmrw-v3-settings-options.*flex-wrap:wrap/s); assert.match(css, /tmrw-v3-diagnostics-output\{white-space:pre-wrap;overflow-x:hidden\}/); assert.match(css, /tmrw-v3-content\{overflow-y:auto\}/); assert.match(css, /white-space:normal;overflow-wrap:anywhere;word-break:break-word/); const effectiveWidthAt390 = Math.min(390, 420); assert.equal(effectiveWidthAt390, 390);
});
