import { POCKET_MATCH_STATE, POCKET_OBSERVATION_TYPE, POCKET_MAX_OBSERVATIONS, POCKET_SOURCE_AUTHORITY } from './constants.mjs';
import { boundedText, digest } from './hash.mjs';
import { pocketDirectThreadRows } from './dm-reader.mjs';
import { pocketGroupRows } from './group-reader.mjs';
import { pocketCallLogRows } from './call-log-reader.mjs';

const freeze = value => Object.freeze(value);
const sameScope = (left, right) => left?.storyId && right?.storyId && left.storyId === right.storyId && left.branchId === right.branchId;
const content = message => ({ id: message?.id || null, from: String(message?.from || ''), text: boundedText(message?.text), timestamp: message?.ts ?? message?.timestamp ?? null, mediaKey: message?.mediaKey || null, deleted: message?.deleted === true, revised: message?.edited === true || message?.revised === true });
const callContent = call => ({ contactId: String(call?.cid || ''), chatId: call?.chatId == null ? null : String(call.chatId), incoming: Boolean(call?.incoming), startedAt: call?.startISO || null, durationText: call?.durText || null, transcriptCount: Array.isArray(call?.transcript) ? call.transcript.length : 0, deleted: call?.deleted === true });

export class PocketNormalizer {
  #mapper; #routes;
  constructor({ identityMapper, routeResolver }) { this.#mapper = identityMapper; this.#routes = routeResolver; }
  async #observation({ snapshot, observationType, sourceId, payload, identity = null, route = null, reason = null, unsupported = false }) {
    const sourceAuthority = snapshot.sourceAuthority || POCKET_SOURCE_AUTHORITY; const identityResult = identity ? await this.#mapper.resolve({ sourceAuthority, sourceType: identity.type, sourceId: identity.id }) : null; const routeResult = route ? await this.#routes.resolve(route) : null;
    let matchState = unsupported ? POCKET_MATCH_STATE.UNSUPPORTED : POCKET_MATCH_STATE.UNRESOLVED; let scope = null; let canonical = {};
    if (!unsupported && identityResult?.state === POCKET_MATCH_STATE.EXACT && (!routeResult || (routeResult.state === POCKET_MATCH_STATE.EXACT && sameScope(identityResult.scope, routeResult.scope)))) { matchState = POCKET_MATCH_STATE.EXACT; scope = identityResult.scope; canonical = { ...identityResult.canonical, ...(routeResult?.canonical || {}) }; }
    else if (!unsupported && (identityResult?.state === POCKET_MATCH_STATE.POSSIBLE || routeResult?.state === POCKET_MATCH_STATE.POSSIBLE)) matchState = POCKET_MATCH_STATE.POSSIBLE;
    else if (!unsupported && ((identityResult && identityResult.state !== POCKET_MATCH_STATE.UNRESOLVED) || (routeResult && routeResult.state !== POCKET_MATCH_STATE.UNRESOLVED))) matchState = POCKET_MATCH_STATE.AMBIGUOUS;
    const rawFingerprint = await digest({ observationType, sourceId, payload }); const observationId = `${observationType}:${sourceId}`;
    return freeze({ observationId, sourceAuthority, observationType, sourceId, sourceVersion: snapshot.sourceVersion, sourceFingerprint: rawFingerprint, content: freeze(structuredClone(payload)), matchState, scope, canonical: freeze(canonical), reason: reason || (matchState === POCKET_MATCH_STATE.EXACT ? null : identityResult?.reason || routeResult?.reason || 'Pocket observation lacks defensible explicit identity and scope evidence.'), sourceMetadata: freeze({ routeKey: route || null, identityType: identity?.type || null, identityId: identity?.id || null, sourceVersion: snapshot.sourceVersion, nonCanonical: true }) });
  }
  async normalize(snapshot, { maxObservations = POCKET_MAX_OBSERVATIONS } = {}) {
    if (!Number.isInteger(maxObservations) || maxObservations < 1 || maxObservations > POCKET_MAX_OBSERVATIONS) throw new TypeError(`maxObservations must be 1-${POCKET_MAX_OBSERVATIONS}`);
    const output = []; const add = async input => { if (output.length < maxObservations) output.push(await this.#observation(input)); };
    const config = snapshot.config; for (const [index, contact] of (Array.isArray(config.contacts) ? config.contacts : []).entries()) { const id = String(contact?.id || '').trim(); await add({ snapshot, observationType: POCKET_OBSERVATION_TYPE.CONTACT, sourceId: id || `missing-contact-${index}`, payload: { contactId: id || null, name: boundedText(contact?.name, 256), avatarHint: contact?.avatar || null }, identity: id ? { type: 'pocket-contact', id } : null, reason: id ? null : 'Pocket contact lacks stable id.', unsupported: !id }); }
    for (const row of pocketDirectThreadRows(config)) { if (row.unsupported) { await add({ snapshot, observationType: POCKET_OBSERVATION_TYPE.DM_MESSAGE, sourceId: `unsupported:${row.threadKey}`, payload: {}, reason: row.reason, unsupported: true }); continue; } const payload = content(row.message); const fingerprint = await digest({ threadKey: row.threadKey, payload }); await add({ snapshot, observationType: POCKET_OBSERVATION_TYPE.DM_MESSAGE, sourceId: `thread:${row.threadKey}:message:${payload.id || fingerprint}:${row.index}`, payload: { threadKey: row.threadKey, contactId: row.contactId, ...payload }, identity: { type: 'pocket-contact', id: row.contactId }, route: row.threadKey }); }
    for (const row of pocketGroupRows(config)) { if (row.unsupported) { await add({ snapshot, observationType: POCKET_OBSERVATION_TYPE.GROUP_MESSAGE, sourceId: `unsupported:${row.groupId || 'group'}`, payload: {}, reason: row.reason, unsupported: true }); continue; } const payload = content(row.message); const fingerprint = await digest({ groupId: row.groupId, payload }); const memberMappings = await Promise.all((Array.isArray(row.group.members) ? row.group.members : []).map(id => this.#mapper.resolve({ sourceType: 'pocket-contact', sourceId: String(id) }))); const groupMapping = await this.#mapper.resolve({ sourceType: 'pocket-group', sourceId: row.groupId }); const groupExact = groupMapping.state === POCKET_MATCH_STATE.EXACT && memberMappings.length > 0 && memberMappings.every(member => member.state === POCKET_MATCH_STATE.EXACT && sameScope(member.scope, groupMapping.scope)); await add({ snapshot, observationType: POCKET_OBSERVATION_TYPE.GROUP_MESSAGE, sourceId: `group:${row.groupId}:message:${payload.id || fingerprint}:${row.index}`, payload: { groupId: row.groupId, groupName: boundedText(row.group.name, 256), memberSourceIds: (row.group.members || []).map(String), ...payload }, identity: groupExact ? { type: 'pocket-group', id: row.groupId } : null, reason: groupExact ? null : 'Pocket group scope or complete member mapping is unproven; quarantined.', unsupported: false }); }
    for (const row of pocketCallLogRows(config)) { const payload = callContent(row.call); const routeKey = payload.chatId ? `${payload.contactId}::${payload.chatId}` : null; const fingerprint = await digest(payload); await add({ snapshot, observationType: POCKET_OBSERVATION_TYPE.CALL_LOG, sourceId: `call:${fingerprint}:${row.index}`, payload: { ...payload, fingerprint }, identity: payload.contactId ? { type: 'pocket-contact', id: payload.contactId } : null, route: routeKey, reason: routeKey ? null : 'Pocket completed Call has no route evidence.' }); }
    return freeze({ observations: freeze(output), truncated: output.length >= maxObservations, sourceRecordsTraversed: (Array.isArray(config.contacts) ? config.contacts.length : 0) + pocketDirectThreadRows(config).length + pocketGroupRows(config).length + pocketCallLogRows(config).length });
  }
}
