import { V3UnitOfWork } from '../../storage/unit-of-work.mjs';
import { requireEventScope } from '../events/event-validator.mjs';
import { canonicalJson, deriveCanonicalEventId } from '../events/idempotency.mjs';
import { prepareDisclosureBundle } from '../knowledge/knowledge-service.mjs';
import { AUDIENCE_KIND } from '../knowledge/audience-policy.mjs';
import { EVIDENCE_BASIS } from '../knowledge/disclosure-observation.mjs';
import { EVIDENCE_FRAGMENT_KIND } from '../knowledge/evidence-fragment.mjs';
import { TIME_ADVANCE_BASIS, TIME_ADVANCE_CONFIDENCE } from '../time/time-advance.mjs';
import { storyClockHeadId } from '../time/clock-projector.mjs';
import { CALL_ACTION, CALL_STATE, isTerminalCallState, transitionCallState } from './call-state-machine.mjs';
import { CALL_EVENT_TYPES } from './call-event-types.mjs';
import { callSessionHeadId, normalizeCallSession } from './call-session.mjs';
import { callTranscriptHeadId, normalizeCallTranscriptEntry } from './call-transcript.mjs';
import { normalizeVoicemail, voicemailHeadId } from './voicemail.mjs';

const MAX_SEQUENCE = Number.MAX_SAFE_INTEGER;
const digest = async value => { const bytes = new TextEncoder().encode(canonicalJson(value)); const hash = await globalThis.crypto.subtle.digest('SHA-256', bytes); return [...new Uint8Array(hash)].map(byte => byte.toString(16).padStart(2, '0')).join(''); };
const stableId = async (kind, scope, value) => `${kind}:${(await digest({ kind, scope, value })).slice(0, 40)}`;
function sourceKey(source, field) { if (!source?.authority || !source?.recordId) throw new TypeError(`${field} requires stable source.authority and source.recordId`); return `${source.authority}:${source.recordId}`; }
function refs(rows) { const seen = new Set(); return Object.freeze(rows.filter(Boolean).filter(row => { const key = `${row.entityType}:${row.id}:${row.role}`; if (seen.has(key)) return false; seen.add(key); return true; })); }

export class CallService {
  #unitOfWork; #events; #metrics = Object.freeze({ operation: 'none' });
  constructor({ database, eventEngine }) { if (!database || !eventEngine) throw new TypeError('CallService requires isolated v3 storage and the canonical Event engine'); this.#unitOfWork = new V3UnitOfWork(database); this.#events = eventEngine; }
  get lastOperationMetrics() { return structuredClone(this.#metrics); }

  async #members(scope, accountIds) {
    return this.#unitOfWork.readonly({ stores: ['accounts', 'instances', 'actors'], scope }, async repositories => {
      const output = [];
      for (const accountId of [...new Set(accountIds)].sort()) {
        const account = await repositories.accounts.get(accountId); const instance = account && await repositories.instances.get(account.ownerInstanceId); const actor = instance && await repositories.actors.get(instance.actorId);
        if (!account || !instance || !actor) throw new Error(`Call participant identity chain is incomplete: ${accountId}`);
        output.push(Object.freeze({ accountId: account.id, actorId: actor.id, instanceId: instance.id }));
      }
      return Object.freeze(output);
    });
  }
  async #eventReplay(scope, source, producer, idempotencyKey) {
    const id = await deriveCanonicalEventId({ scope, source: { authority: source?.authority, recordId: source?.recordId }, producer, idempotencyKey }); return this.#events.getEvent(scope, id);
  }
  async #disclosure(scope, stableKey, session, source, { text = null, transcript = false, voicemail = false } = {}) {
    const safeText = text || `Private call ${session.callSessionId}`; const bundle = {
      claim: { claimType: voicemail ? 'calls.voicemail-content.v1' : (transcript ? 'calls.transcript-content.v1' : 'calls.session.v1'), subject: { kind: 'event', id: session.callSessionId }, safeSummary: safeText, certainty: 'confirmed', currentness: 'current' },
      audience: { kind: AUDIENCE_KIND.PRIVATE_EXPLICIT, actorIds: session.participantActorIds, instanceIds: session.participantInstanceIds },
      fragments: [{ key: 'content', kind: transcript ? EVIDENCE_FRAGMENT_KIND.TRANSCRIPT_SEGMENT : EVIDENCE_FRAGMENT_KIND.EVENT_FIELD, safeText, sourceField: transcript ? 'text' : 'callSession' }],
      observations: session.participants.map(member => ({ fragmentKeys: ['content'], targetActorId: member.actorId, targetInstanceId: member.instanceId, confidence: 'confirmed', evidence: { basis: transcript ? (member.accountId === session.callingAccountId ? EVIDENCE_BASIS.DIRECT_PARTICIPANT : EVIDENCE_BASIS.EXPLICIT_RECIPIENT) : EVIDENCE_BASIS.DIRECT_PARTICIPANT, sourceEventId: null, sourceActorId: session.initiatingActualActorId, sourceDeviceId: session.initiatingDeviceId, sourceAccountId: session.callingAccountId, provenanceAuthority: source.authority, provenanceRecordId: `${source.recordId}:knowledge:${member.accountId}` } })),
    };
    return prepareDisclosureBundle({ scope, stableKey, bundle });
  }

  async initiate({ scope: inputScope, participantAccountIds = null, callingAccountId, calledAccountId, actualActorId, actualInstanceId, deviceId, sourceMode = 'live', handoff = null, source, producer = 'call-service', idempotencyKey = null }) {
    const scope = requireEventScope(inputScope); const accounts = participantAccountIds || [callingAccountId, calledAccountId]; const members = await this.#members(scope, accounts);
    const caller = members.find(member => member.accountId === callingAccountId); const called = members.find(member => member.accountId === calledAccountId); if (!caller || !called || caller.accountId === called.accountId) throw new TypeError('Canonical Calls require distinct calling and called Accounts');
    const identity = await this.#unitOfWork.readonly({ stores: ['actors', 'instances', 'devices'], scope }, async repositories => ({ actor: await repositories.actors.get(actualActorId), instance: await repositories.instances.get(actualInstanceId), device: await repositories.devices.get(deviceId) }));
    if (!identity.actor || !identity.instance || identity.instance.actorId !== identity.actor.id || !identity.device) throw new TypeError('Call actual actor/instance/device is invalid');
    const callSessionId = await stableId('call-session', scope, { source: sourceKey(source, 'Call Session'), callingAccountId, calledAccountId, participantAccountIds: members.map(member => member.accountId) });
    const existing = await this.getSession({ scope, callSessionId }); if (existing) return Object.freeze({ session: existing, event: await this.#eventReplay(scope, source, producer, idempotencyKey || `call:${callSessionId}`), replayed: true });
    const session = normalizeCallSession({ callSessionId, participants: members, callingAccountId, calledAccountId, initiatingActualActorId: actualActorId, initiatingActualInstanceId: actualInstanceId, initiatingDeviceId: deviceId, sourceMode });
    const bundle = await this.#disclosure(scope, `call:${callSessionId}`, session, source);
    const result = await this.#events.append({ scope, eventType: CALL_EVENT_TYPES.SESSION_INITIATED, payload: { session, knowledgeDisclosures: [bundle], ...(handoff ? { handoff: structuredClone(handoff) } : {}) }, references: refs([...members.flatMap(member => [{ entityType: 'account', id: member.accountId, role: 'call-participant-account' }, { entityType: 'actor', id: member.actorId, role: 'call-participant-actor' }, { entityType: 'character-instance', id: member.instanceId, role: 'call-participant-instance' }]), { entityType: 'device', id: deviceId, role: 'call-initiating-device' }, { entityType: 'actor', id: actualActorId, role: 'call-actual-actor' }]), source, producer, idempotencyKey: idempotencyKey || `call:${callSessionId}` });
    this.#metrics = Object.freeze({ operation: 'initiate-call', ...this.#events.lastOperationMetrics }); return Object.freeze({ session: await this.getSession({ scope, callSessionId }), event: result.event, replayed: result.replayed });
  }

  async transition({ scope: inputScope, callSessionId, action, actualActorId = null, actualInstanceId = null, deviceId = null, measuredDurationMs = null, handoff = null, source, producer = 'call-service', idempotencyKey, sourceEventId = null }) {
    const scope = requireEventScope(inputScope); const existingEvent = await this.#eventReplay(scope, source, producer, idempotencyKey); if (existingEvent) { const result = await this.#events.append({ scope, eventType: existingEvent.eventType, payload: existingEvent.payload, references: existingEvent.references, causes: existingEvent.causes, source, producer, idempotencyKey }); return Object.freeze({ session: await this.getSession({ scope, callSessionId }), event: result.event, replayed: true }); }
    const session = await this.getSession({ scope, callSessionId }); if (!session || isTerminalCallState(session.state)) throw new TypeError('Call Session is not transitionable in this Story/Branch');
    if ((actualActorId || actualInstanceId || deviceId) && (!actualActorId || !actualInstanceId || !deviceId)) throw new TypeError('Call lifecycle provenance requires Actor, Character Instance, and Device together');
    const state = transitionCallState(session.state, action); let storyClockAdvance = null;
    if (action === CALL_ACTION.END) { const durationMs = Number(measuredDurationMs); if (!Number.isSafeInteger(durationMs) || durationMs < 0) throw new TypeError('Ending an active Call requires explicit measuredDurationMs'); const clock = await this.#unitOfWork.readonly({ stores: ['clockCheckpoints'], scope }, repositories => repositories.clockCheckpoints.get(storyClockHeadId(scope))); storyClockAdvance = Object.freeze({ durationMs, basis: TIME_ADVANCE_BASIS.CALL_MEASURED, confidence: TIME_ADVANCE_CONFIDENCE.MEASURED, sourceActivityId: callSessionId, policyVersion: 'phase9-call-measured-v1', explanation: 'Measured connected Call Session duration' }); const payload = { callSessionId, action, state, actualActorId, actualInstanceId, deviceId, storyClockAdvance, priorChronologyEventId: clock?.state?.lastChronologyEventId ?? null, ...(handoff ? { handoff: structuredClone(handoff) } : {}) }; const result = await this.#events.append({ scope, eventType: CALL_EVENT_TYPES.SESSION_TRANSITIONED, payload, references: refs([{ entityType: 'account', id: session.callingAccountId, role: 'calling-account' }, { entityType: 'account', id: session.calledAccountId, role: 'called-account' }, actualActorId && { entityType: 'actor', id: actualActorId, role: 'call-lifecycle-actual-actor' }, actualInstanceId && { entityType: 'character-instance', id: actualInstanceId, role: 'call-lifecycle-actual-instance' }, deviceId && { entityType: 'device', id: deviceId, role: 'call-lifecycle-device' }]), causes: [session.sourceInitiatedEventId, sourceEventId].filter(Boolean), source, producer, idempotencyKey }); this.#metrics = Object.freeze({ operation: 'transition-call', ...this.#events.lastOperationMetrics }); return Object.freeze({ session: await this.getSession({ scope, callSessionId }), event: result.event, replayed: result.replayed }); }
    const payload = { callSessionId, action, state, actualActorId, actualInstanceId, deviceId, storyClockAdvance: null, priorChronologyEventId: null, ...(handoff ? { handoff: structuredClone(handoff) } : {}) }; const result = await this.#events.append({ scope, eventType: CALL_EVENT_TYPES.SESSION_TRANSITIONED, payload, references: refs([{ entityType: 'account', id: session.callingAccountId, role: 'calling-account' }, { entityType: 'account', id: session.calledAccountId, role: 'called-account' }, actualActorId && { entityType: 'actor', id: actualActorId, role: 'call-lifecycle-actual-actor' }, actualInstanceId && { entityType: 'character-instance', id: actualInstanceId, role: 'call-lifecycle-actual-instance' }, deviceId && { entityType: 'device', id: deviceId, role: 'call-lifecycle-device' }]), causes: [session.sourceInitiatedEventId, sourceEventId].filter(Boolean), source, producer, idempotencyKey }); this.#metrics = Object.freeze({ operation: 'transition-call', ...this.#events.lastOperationMetrics }); return Object.freeze({ session: await this.getSession({ scope, callSessionId }), event: result.event, replayed: result.replayed });
  }

  async addTranscript({ scope: inputScope, callSessionId, speakerAccountId, actualAuthorActorId, actualAuthorInstanceId, deviceId, text, sourceMode = 'live', handoff = null, aiJobCommit = null, causeEventIds = [], source, producer = 'call-service', idempotencyKey }) {
    const scope = requireEventScope(inputScope); const session = await this.getSession({ scope, callSessionId }); if (!session || session.state !== CALL_STATE.ACTIVE) throw new TypeError('Text Call transcript requires an active Call Session'); if (!session.participantAccountIds.includes(speakerAccountId)) throw new TypeError('Transcript speaker is not a Call participant');
    const entryId = await stableId('call-transcript', scope, { source: sourceKey(source, 'Call transcript'), callSessionId, speakerAccountId }); const transcript = normalizeCallTranscriptEntry({ transcriptEntryId: entryId, callSessionId, speakerAccountId, actualAuthorActorId, actualAuthorInstanceId, deviceId, text, sourceMode }); const bundle = await this.#disclosure(scope, `call-transcript:${entryId}`, session, source, { text, transcript: true });
    const result = await this.#events.append({ scope, eventType: CALL_EVENT_TYPES.TRANSCRIPT_ADDED, payload: { transcript, recipientAccountIds: session.participantAccountIds, knowledgeDisclosures: [bundle], ...(handoff ? { handoff: structuredClone(handoff) } : {}), ...(aiJobCommit ? { aiJobCommit: structuredClone(aiJobCommit) } : {}) }, references: refs([{ entityType: 'account', id: speakerAccountId, role: 'transcript-speaker-account' }, { entityType: 'actor', id: actualAuthorActorId, role: 'transcript-actual-author' }, { entityType: 'character-instance', id: actualAuthorInstanceId, role: 'transcript-actual-instance' }, { entityType: 'device', id: deviceId, role: 'transcript-device' }]), causes: [...new Set([session.sourceInitiatedEventId, ...(causeEventIds || []), aiJobCommit?.sourceEventId].filter(Boolean))], source, producer, idempotencyKey }); this.#metrics = Object.freeze({ operation: 'add-call-transcript', ...this.#events.lastOperationMetrics }); return Object.freeze({ transcript: await this.getTranscript({ scope, transcriptEntryId: entryId }), event: result.event, replayed: result.replayed });
  }

  async leaveVoicemail({ scope: inputScope, callSessionId, callerAccountId, recipientAccountId, actualAuthorActorId, actualAuthorInstanceId, deviceId, text, source, producer = 'call-service', idempotencyKey, aiJobCommit = null, causeEventIds = [] }) {
    const scope = requireEventScope(inputScope); const session = await this.getSession({ scope, callSessionId }); if (!session) throw new TypeError('Voicemail requires a scoped Call Session'); if (!session.participantAccountIds.includes(callerAccountId) || !session.participantAccountIds.includes(recipientAccountId) || callerAccountId === recipientAccountId) throw new TypeError('Voicemail caller/recipient must be distinct Call participants'); if (![CALL_STATE.MISSED, CALL_STATE.DECLINED, CALL_STATE.ENDED, CALL_STATE.CANCELLED].includes(session.state)) throw new TypeError('Voicemail requires a terminal or missed Call Session');
    const voicemailId = await stableId('call-voicemail', scope, { source: sourceKey(source, 'Voicemail'), callSessionId, callerAccountId, recipientAccountId }); const voicemail = normalizeVoicemail({ voicemailId, callSessionId, callerAccountId, recipientAccountId, actualAuthorActorId, actualAuthorInstanceId, deviceId, text }); const bundle = await this.#disclosure(scope, `call-voicemail:${voicemailId}`, session, source, { text, voicemail: true });
    const result = await this.#events.append({ scope, eventType: CALL_EVENT_TYPES.VOICEMAIL_LEFT, payload: { voicemail, knowledgeDisclosures: [bundle], ...(aiJobCommit ? { aiJobCommit: structuredClone(aiJobCommit) } : {}) }, references: refs([{ entityType: 'account', id: callerAccountId, role: 'voicemail-caller-account' }, { entityType: 'account', id: recipientAccountId, role: 'voicemail-recipient-account' }, { entityType: 'actor', id: actualAuthorActorId, role: 'voicemail-actual-author' }, { entityType: 'character-instance', id: actualAuthorInstanceId, role: 'voicemail-actual-instance' }, { entityType: 'device', id: deviceId, role: 'voicemail-device' }]), causes: [...new Set([session.sourceInitiatedEventId, ...(causeEventIds || []), aiJobCommit?.sourceEventId].filter(Boolean))], source, producer, idempotencyKey }); this.#metrics = Object.freeze({ operation: 'leave-text-voicemail', ...this.#events.lastOperationMetrics }); return Object.freeze({ voicemail: await this.getVoicemail({ scope, voicemailId }), event: result.event, replayed: result.replayed });
  }

  async getSession({ scope: inputScope, callSessionId }) { const scope = requireEventScope(inputScope); return this.#unitOfWork.readonly({ stores: ['callSessions'], scope }, repositories => repositories.callSessions.get(callSessionHeadId(scope, callSessionId))); }
  async getTranscript({ scope: inputScope, transcriptEntryId }) { const scope = requireEventScope(inputScope); return this.#unitOfWork.readonly({ stores: ['callTranscripts'], scope }, repositories => repositories.callTranscripts.get(callTranscriptHeadId(scope, transcriptEntryId))); }
  async getVoicemail({ scope: inputScope, voicemailId }) { const scope = requireEventScope(inputScope); return this.#unitOfWork.readonly({ stores: ['callVoicemails'], scope }, repositories => repositories.callVoicemails.get(voicemailHeadId(scope, voicemailId))); }
  async listVoicemails({ scope: inputScope, viewerAccountId, limit = 50 }) { const scope = requireEventScope(inputScope); const rows = await this.#unitOfWork.readonly({ stores: ['callVoicemails'], scope }, async repositories => { const [incoming, outgoing] = await Promise.all([repositories.callVoicemails.listByIndexRange('by_scope_recipient_reverse_sequence', { lower: [scope.storyId, scope.branchId, viewerAccountId, 0], upper: [scope.storyId, scope.branchId, viewerAccountId, MAX_SEQUENCE] }, { limit }), repositories.callVoicemails.listByIndexRange('by_scope_caller_reverse_sequence', { lower: [scope.storyId, scope.branchId, viewerAccountId, 0], upper: [scope.storyId, scope.branchId, viewerAccountId, MAX_SEQUENCE] }, { limit })]); return [...new Map([...incoming, ...outgoing].map(row => [row.voicemailId, row])).values()].sort((a, b) => a.sourceEventSequence - b.sourceEventSequence).slice(-limit); }); this.#metrics = Object.freeze({ operation: 'list-voicemails', directRows: rows.length, eventHistoryScans: 0 }); return Object.freeze(rows); }
  async listCalls({ scope: inputScope, viewerAccountId, limit = 50 }) { const scope = requireEventScope(inputScope); const rows = await this.#unitOfWork.readonly({ stores: ['callParticipants', 'callSessions'], scope }, async repositories => { const participants = await repositories.callParticipants.listByIndex('by_scope_account', [scope.storyId, scope.branchId, viewerAccountId]); const sessions = await Promise.all(participants.map(row => repositories.callSessions.get(callSessionHeadId(scope, row.callSessionId)))); return sessions.filter(Boolean).sort((a, b) => b.sourceInitiatedSequence - a.sourceInitiatedSequence || a.callSessionId.localeCompare(b.callSessionId)).slice(0, limit); }); this.#metrics = Object.freeze({ operation: 'list-calls', directCallParticipantIndexRows: rows.length, eventHistoryScans: 0 }); return Object.freeze(rows); }
  async listTranscript({ scope: inputScope, viewerAccountId, callSessionId, limit = 100 }) { const scope = requireEventScope(inputScope); const rows = await this.#unitOfWork.readonly({ stores: ['callParticipants', 'callTranscripts', 'callTranscriptRecipients'], scope }, async repositories => { const participant = await repositories.callParticipants.getByIndex('by_scope_session_account', [scope.storyId, scope.branchId, callSessionId, viewerAccountId]); if (!participant) return []; const recipients = await repositories.callTranscriptRecipients.listByIndexRange('by_scope_session_account_reverse_sequence', { lower: [scope.storyId, scope.branchId, callSessionId, viewerAccountId, 0], upper: [scope.storyId, scope.branchId, callSessionId, viewerAccountId, MAX_SEQUENCE] }, { limit }); return Promise.all(recipients.map(row => repositories.callTranscripts.get(callTranscriptHeadId(scope, row.transcriptEntryId)))); }); const active = rows.filter(Boolean).sort((a, b) => a.sourceEventSequence - b.sourceEventSequence || a.transcriptEntryId.localeCompare(b.transcriptEntryId)); this.#metrics = Object.freeze({ operation: 'list-call-transcript', directTranscriptIndexRows: active.length, eventHistoryScans: 0 }); return Object.freeze(active); }
}
