import { V3UnitOfWork } from '../../storage/unit-of-work.mjs';
import { requireEventScope } from '../events/event-validator.mjs';
import { requireText } from '../identity/identity-record.mjs';
import { NOTIFICATION_READ_STATE, NOTIFICATION_VISIBLE_STATE } from './notification.mjs';

const MAX_SEQUENCE = Number.MAX_SAFE_INTEGER;
const APP_IDS = Object.freeze(['messages', 'calls', 'feed', 'live']);
const limitValue = value => { const limit = Number(value ?? 25); if (!Number.isInteger(limit) || limit < 1 || limit > 100) throw new TypeError('notification page limit must be 1-100'); return limit; };
const parseCursor = value => { if (!value) return null; const split = String(value).indexOf(':'); const sequence = Number(String(value).slice(0, split)); const id = String(value).slice(split + 1); if (split < 1 || !Number.isSafeInteger(sequence) || !id) throw new TypeError('Invalid notification cursor'); return { sequence, id }; };
const cursorFor = row => `${row.reverseSequence}:${row.notificationId}`;

export class NotificationService {
  #unitOfWork; #now; #lastMetrics = Object.freeze({ indexedRowsRead: 0, fullEventHistoryScans: 0, fullStoryScans: 0, fullBranchScans: 0, writesDuringRead: 0 });
  constructor({ database, now = () => new Date().toISOString() }) { if (!database) throw new TypeError('NotificationService requires the isolated v3 database'); this.#unitOfWork = new V3UnitOfWork(database); this.#now = now; }
  get lastMetrics() { return this.#lastMetrics; }
  async #assertPerspective(repositories, scope, accountId, deviceId) { const account = await repositories.accounts.get(requireText(accountId, 'accountId')); const device = await repositories.devices.get(requireText(deviceId, 'deviceId')); if (!account || !device || account.ownerInstanceId !== device.ownerInstanceId || !account.deviceIds.includes(device.id)) throw new Error('Notification perspective Account/Device mismatch'); return { account, device }; }
  async listRecent({ scope: inputScope, accountId, deviceId, limit: inputLimit = 25, cursor = null, grouped = true }) {
    const scope = requireEventScope(inputScope); const limit = limitValue(inputLimit); const parsed = parseCursor(cursor);
    const page = await this.#unitOfWork.readonly({ stores: ['notificationProjections', 'accounts', 'devices', 'phoneStates'], scope }, async repositories => {
      await this.#assertPerspective(repositories, scope, accountId, deviceId); const fetchLimit = grouped ? Math.min(100, limit * 3) : limit;
      const rows = await repositories.notificationProjections.listByIndexRange('by_scope_device_visible_reverse', { lower: parsed ? [scope.storyId, scope.branchId, deviceId, NOTIFICATION_VISIBLE_STATE.VISIBLE, parsed.sequence, parsed.id] : [scope.storyId, scope.branchId, deviceId, NOTIFICATION_VISIBLE_STATE.VISIBLE, 0, ''], lowerOpen: Boolean(parsed), upper: [scope.storyId, scope.branchId, deviceId, NOTIFICATION_VISIBLE_STATE.VISIBLE, MAX_SEQUENCE, '\uffff'] }, { limit: fetchLimit });
      const phone = await repositories.phoneStates.getByIndex('by_scope_device', [scope.storyId, scope.branchId, deviceId]); const scopedRows = rows.filter(item => item.recipientAccountId === accountId).map(item => ({ ...item, currentHolderActorId: phone?.currentHolderActorId || null, currentHolderInstanceId: phone?.currentHolderInstanceId || null })); if (!grouped) return { items: scopedRows.slice(0, limit), rowsRead: rows.length };
      const groups = new Map(); for (const item of scopedRows) { if (!groups.has(item.groupingKey)) groups.set(item.groupingKey, { ...item, groupedNotificationIds: [], groupedSourceActorIds: new Set() }); const group = groups.get(item.groupingKey); group.groupedNotificationIds.push(item.notificationId); if (item.sourceActorId) group.groupedSourceActorIds.add(item.sourceActorId); }
      const items = [...groups.values()].slice(0, limit).map(item => Object.freeze({ ...item, groupCount: item.groupedNotificationIds.length, groupedNotificationIds: Object.freeze(item.groupedNotificationIds), groupedSourceActorIds: Object.freeze([...item.groupedSourceActorIds].sort()) })); return { items, rowsRead: rows.length };
    });
    const items = Object.freeze(page.items); const last = items.at(-1); this.#lastMetrics = Object.freeze({ indexedRowsRead: page.rowsRead, fullEventHistoryScans: 0, fullStoryScans: 0, fullBranchScans: 0, writesDuringRead: 0 }); return Object.freeze({ items, nextCursor: items.length >= limit && last ? cursorFor(last) : null });
  }
  async getBadgeCount({ scope: inputScope, accountId, deviceId, appId }) { const scope = requireEventScope(inputScope); requireText(appId, 'appId'); const count = await this.#unitOfWork.readonly({ stores: ['notificationProjections', 'accounts', 'devices'], scope }, async repositories => { await this.#assertPerspective(repositories, scope, accountId, deviceId); return repositories.notificationProjections.countByIndex('by_scope_device_app_read', [scope.storyId, scope.branchId, deviceId, appId, NOTIFICATION_READ_STATE.UNREAD]); }); this.#lastMetrics = Object.freeze({ indexedRowsRead: 1, fullEventHistoryScans: 0, fullStoryScans: 0, fullBranchScans: 0, writesDuringRead: 0 }); return count; }
  async getBadges({ scope, accountId, deviceId }) { const entries = await Promise.all(APP_IDS.map(async appId => [appId, await this.getBadgeCount({ scope, accountId, deviceId, appId })])); return Object.freeze(Object.fromEntries(entries)); }
  async #changeLocalState({ scope: inputScope, notificationId, accountId, deviceId, readState, visibleState }) { const scope = requireEventScope(inputScope); return this.#unitOfWork.readwrite({ stores: ['notificationProjections', 'accounts', 'devices'], scope }, async repositories => { await this.#assertPerspective(repositories, scope, accountId, deviceId); const current = await repositories.notificationProjections.get(requireText(notificationId, 'notificationId')); if (!current || current.recipientAccountId !== accountId || current.recipientDeviceId !== deviceId) throw new Error('Notification is not visible in this phone perspective'); const next = Object.freeze({ ...current, readState: readState || current.readState, visibleState: visibleState || current.visibleState, localStateRevision: current.localStateRevision + 1, localStateUpdatedAt: this.#now() }); await repositories.notificationProjections.put(next); return next; }); }
  markRead(input) { return this.#changeLocalState({ ...input, readState: NOTIFICATION_READ_STATE.READ }); }
  dismiss(input) { return this.#changeLocalState({ ...input, readState: NOTIFICATION_READ_STATE.READ, visibleState: NOTIFICATION_VISIBLE_STATE.DISMISSED }); }
  async resolveSource({ scope: inputScope, notificationId, accountId, deviceId }) { const scope = requireEventScope(inputScope); return this.#unitOfWork.readonly({ stores: ['notificationProjections', 'accounts', 'devices', 'events'], scope }, async repositories => { await this.#assertPerspective(repositories, scope, accountId, deviceId); const item = await repositories.notificationProjections.get(requireText(notificationId, 'notificationId')); if (!item || item.recipientAccountId !== accountId || item.recipientDeviceId !== deviceId || item.visibleState !== NOTIFICATION_VISIBLE_STATE.VISIBLE) return Object.freeze({ available: false, reason: 'not-visible' }); const event = await repositories.events.get(item.sourceEventId); if (!event || event.status !== 'active') return Object.freeze({ available: false, reason: 'source-unavailable' }); const route = item.navigation.kind === 'thread' ? 'messages' : item.navigation.kind === 'call' ? 'calls' : item.navigation.kind === 'post' ? 'feed' : item.navigation.kind === 'live' ? 'live' : item.navigation.kind === 'account' ? 'insungram' : null; return Object.freeze(route ? { available: true, route, source: structuredClone(item.navigation) } : { available: false, reason: 'unsupported-source' }); }); }
  async phoneWorld({ scope, accountId, deviceId, recentLimit = 5 }) { const [badges, recent] = await Promise.all([this.getBadges({ scope, accountId, deviceId }), this.listRecent({ scope, accountId, deviceId, limit: recentLimit })]); return Object.freeze({ badges, recent: recent.items, unreadTotal: Object.values(badges).reduce((sum, value) => sum + value, 0), activeLiveAlerts: badges.live, canonicalWrites: 0 }); }
}
