import { createPreviewIcon } from './app-icons.mjs';

const el = (document, tag, text = '') => { const node = document.createElement(tag); node.textContent = text; return node; };
const icon = (document, name, size) => createPreviewIcon({ document, name, size });
const TONES = Object.freeze(['peach', 'cream', 'mint', 'sky', 'sand', 'rose', 'lavender']);
import { renderAppEmptyState, renderInlineNotice } from './app-empty-state.mjs';
const emptyState = (document, text) => renderAppEmptyState({ document, app: 'notes', title: text, compact: true });

export function renderNotes({ document, items = [], authorizationGranted = true, error = null, selectedRecordId = null, formMode = null, pendingDeleteRecordId = null, onOpen, onStartCreate, onStartEdit, onCancelForm, onSave, onRequestDelete, onCancelDelete, onConfirmDelete }) {
  const root = el(document, 'section'); root.className = 'tmrw-v3-notes tmrw-phone-personal-app tmrw-phone-notes-board';
  if (!authorizationGranted) { root.append(emptyState(document, 'โทรศัพท์เครื่องนี้ยังล็อกอยู่')); return root; }
  if (error) { root.append(renderInlineNotice({ document, tone:'error', title:'เปิด Notes ยังไม่สำเร็จ', detail:'ข้อมูลเดิมยังอยู่ ลองกลับเข้ามาใหม่อีกครั้ง' })); return root; }
  const selected = items.find(item => item.recordId === selectedRecordId) || null;

  if (formMode) {
    const editing = formMode === 'edit' && selected;
    const form = el(document, 'section'); form.className = 'tmrw-v3-note-form tmrw-phone-personal-detail tmrw-phone-note-detail'; form.dataset.noteForm = editing ? 'edit' : 'new'; const handle = el(document, 'i'); form.append(handle); const header = el(document, 'header'); const copy = el(document, 'div'); copy.append(el(document, 'small', editing ? 'NOTE · EDIT' : 'NOTE · NEW'), el(document, 'h2', editing ? (selected.title || 'Untitled note') : 'New note')); const close = el(document, 'button'); close.type = 'button'; close.append(icon(document, 'close', 20)); close.addEventListener('click', () => onCancelForm?.()); header.append(copy, close); form.append(header);
    const title = el(document, 'input'); title.type = 'text'; title.value = editing ? (selected.title || '') : ''; title.placeholder = 'Title'; title.setAttribute('aria-label', 'Note title'); const body = el(document, 'textarea'); body.value = editing ? (selected.text || '') : ''; body.placeholder = 'Write a note…'; body.setAttribute('aria-label', 'Note text'); const controls = el(document, 'div'); controls.className = 'tmrw-v3-note-form-controls'; const cancel = el(document, 'button', 'Cancel'); cancel.type = 'button'; cancel.dataset.noteAction = 'cancel-form'; cancel.addEventListener('click', () => onCancelForm?.()); const save = el(document, 'button', editing ? 'Save changes' : 'Create note'); save.type = 'button'; save.dataset.noteAction = 'save'; const sync = () => { save.disabled = !String(title.value || '').trim() && !String(body.value || '').trim(); }; title.addEventListener('input', sync); body.addEventListener('input', sync); sync(); let busy = false; save.addEventListener('click', () => { if (busy || save.disabled) return; busy = true; save.disabled = true; void Promise.resolve(onSave?.({ recordId: editing ? selected.recordId : null, title: String(title.value || '').trim(), text: String(body.value || '').trim() })).finally(() => { busy = false; }); }); controls.append(cancel, save); form.append(title, body, controls); root.append(form); return root;
  }

  if (selected) {
    const detail = el(document, 'section'); detail.className = 'tmrw-v3-note-details tmrw-phone-personal-detail tmrw-phone-note-detail'; detail.dataset.noteDetailsId = selected.recordId; detail.append(el(document, 'i')); const header = el(document, 'header'); const copy = el(document, 'div'); copy.append(el(document, 'small', selected.updatedAt || 'NOTE'), el(document, 'h2', selected.title || 'Untitled note')); const close = el(document, 'button'); close.type = 'button'; close.append(icon(document, 'close', 20)); close.addEventListener('click', () => onOpen?.(null)); header.append(copy, close); detail.append(header); const badge = el(document, 'div'); badge.className = 'tmrw-phone-detail-badges'; badge.append(el(document, 'span', 'Note')); detail.append(badge); const body = el(document, 'article', selected.text || 'ยังไม่มีรายละเอียด'); body.className = 'tmrw-phone-note-detail-body'; detail.append(body);
    if (pendingDeleteRecordId === selected.recordId) { detail.append(el(document, 'p', 'Delete this note?')); const cancel = el(document, 'button', 'Cancel'); cancel.type = 'button'; cancel.dataset.noteAction = 'cancel-delete'; cancel.addEventListener('click', () => onCancelDelete?.()); const confirm = el(document, 'button', 'Delete note'); confirm.type = 'button'; confirm.dataset.noteAction = 'confirm-delete'; let busy = false; confirm.addEventListener('click', () => { if (busy || confirm.disabled) return; busy = true; confirm.disabled = true; void Promise.resolve(onConfirmDelete?.(selected)).finally(() => { busy = false; }); }); detail.append(cancel, confirm); } else { const edit = el(document, 'button', 'Edit'); edit.type = 'button'; edit.dataset.noteAction = 'edit'; edit.addEventListener('click', () => onStartEdit?.()); const remove = el(document, 'button', 'Delete'); remove.type = 'button'; remove.dataset.noteAction = 'request-delete'; remove.addEventListener('click', () => onRequestDelete?.(selected.recordId)); detail.append(edit, remove); }
    root.append(detail); return root;
  }

  const search = el(document, 'label'); search.className = 'tmrw-phone-personal-search tmrw-phone-soft-search'; search.append(icon(document, 'search', 20)); const searchInput = el(document, 'input'); searchInput.type = 'search'; searchInput.placeholder = 'Search notes...'; searchInput.setAttribute('aria-label', 'Search notes'); search.append(searchInput); root.append(search);
  const chips = el(document, 'div'); chips.className = 'tmrw-phone-filter-chips tmrw-phone-soft-chips'; const all = el(document, 'button'); all.type = 'button'; all.className = 'is-active'; all.append(icon(document, 'gallery', 14), el(document, 'span', 'All')); const pinned = el(document, 'button'); pinned.type = 'button'; pinned.disabled = true; pinned.setAttribute('aria-label', 'Pinned ยังไม่มีข้อมูล'); pinned.append(icon(document, 'notes', 14), el(document, 'span', 'Pinned')); const filter = el(document, 'button'); filter.type = 'button'; filter.disabled = true; filter.setAttribute('aria-label', 'ตัวกรองเพิ่มเติมยังไม่พร้อมใช้งาน'); filter.append(icon(document, 'settings', 15)); chips.append(all, pinned, filter); root.append(chips);

  const board = el(document, 'div'); board.className = 'tmrw-phone-note-board'; const cards = [];
  items.forEach((item, index) => { const button = el(document, 'button'); button.type = 'button'; button.className = `tmrw-phone-note-board-card tone-${TONES[index % TONES.length]}`; button.dataset.noteRecordId = item.recordId; const meta = el(document, 'div'); meta.className = 'tmrw-phone-note-board-meta'; meta.append(el(document, 'span', 'NOTE')); button.append(meta, el(document, 'h3', item.title || 'Untitled note'), el(document, 'p', item.text || 'ยังไม่มีรายละเอียด')); const footer = el(document, 'footer'); footer.append(el(document, 'span', 'Note'), el(document, 'time', item.updatedAt || '')); button.append(footer); button.addEventListener('click', () => onOpen?.(item.recordId)); board.append(button); cards.push({ button, item }); });
  if (!items.length) board.append(emptyState(document, 'ยังไม่มีโน้ต')); root.append(board);
  searchInput.addEventListener('input', () => { const q = String(searchInput.value || '').trim().toLocaleLowerCase(); for (const { button, item } of cards) button.hidden = Boolean(q) && !`${item.title || ''} ${item.text || ''}`.toLocaleLowerCase().includes(q); });
  const create = el(document, 'button', '+'); create.type = 'button'; create.className = 'tmrw-phone-personal-fab'; create.dataset.noteAction = 'new'; create.setAttribute('aria-label', 'Create a new private note'); create.addEventListener('click', () => onStartCreate?.()); root.append(create); return root;
}
